// Code generated by dol build. Only Generate by tools if not existed.
// source: app.go

package utils

// Error struct
type Error struct {
	Code int
	Msg  string
}

func (e Error) Error() string {
	return e.Msg
}

// AppAction defined
func AppAction(v interface{}) (interface{}, error) {
	return nil, Error{Msg: "No implementation found"}
}

// M defined
type M map[string]interface{}
