// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package types

// Fail defined 失败返回
type Fail struct {
	// 错误编码
	Code int `json:"code" xml:"code" example:"500"`
	// 错误信息
	Msg string `json:"msg,omitempty" xml:"msg" example:"status bad request"`
}
