apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: hello
  name: hello
  namespace: dolphin
binaryData:
data:
  app.properties: |-
    app.name = hello
    app.mode = debug
    http.port = 8082
