apiVersion: v1
kind: Service
metadata:
  name: scene
  namespace: dolphin
  labels:
    app: scene
    service: scene
spec:
  ports:
  - name: 80tcp01
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: scene
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
