// Code generated by dol build. Only Generate by tools if not existed.
// source: app.go

package api

import (
	"context"
	"path"

	"github.com/2637309949/dolphin/packages/logrus"
	"github.com/2637309949/dolphin/packages/oauth2/errors"
	"github.com/2637309949/dolphin/packages/oauth2/generates"
	"github.com/2637309949/dolphin/packages/oauth2/manage"
	"github.com/2637309949/dolphin/packages/oauth2/server"
	"github.com/2637309949/dolphin/packages/web"
	"github.com/spf13/viper"
	"golang.org/x/oauth2"
)

var (
	App *Dolphin
	Run func() error
)

// A Hook is a pair of start and stop callbacks, either of which can be nil,
type Hook struct {
}

// OnStart defined OnStart
func (h *Hook) OnStart(ctx context.Context) error {
	go func() {
		logrus.Infof(context.TODO(), "http listen on port%v", viper.GetString("http.port"))
		err := web.Run(viper.GetString("http.port"))
		if err != nil {
			logrus.Fatal(context.TODO(), err)
		}
	}()
	return nil
}

// OnStop defined OnStop
func (h *Hook) OnStop(ctx context.Context) error {
	return nil
}

// NewLifeHook defined TODO
func NewLifeHook() lifeHook {
	return &Hook{}
}

// WithLifecycle defined TODO
func WithLifecycle() Option {
	return func(dol *Dolphin) {
		dol.Lifecycle = &lifecycleWrapper{}
		dol.Append(NewLifeHook())
	}
}

// WithManager defined TODO
func WithManager() Option {
	return func(dol *Dolphin) {
		dol.Manager = NewDefaultManager()
	}
}

// WithManager defined TODO
func WithIdentity() Option {
	osHost, httpPrefix := viper.GetString("oauth.server"), viper.GetString("http.prefix")
	authUrl := osHost + path.Join(httpPrefix, SysCasInstance.Authorize.RelativePath)
	tokenUrl := osHost + path.Join(httpPrefix, SysCasInstance.Token.RelativePath)
	endpoint := oauth2.Endpoint{AuthURL: authUrl, TokenURL: tokenUrl}
	redirectURL := viper.GetString("oauth.client") + path.Join(viper.GetString("http.prefix"), SysCasInstance.Oauth2.RelativePath)
	OA2Cfg = oauth2.Config{ClientID: viper.GetString("oauth.id"), ClientSecret: viper.GetString("oauth.secret"), Scopes: []string{"admin"}, RedirectURL: redirectURL, Endpoint: endpoint}
	qrRedirectURL := viper.GetString("oauth.client") + path.Join(viper.GetString("http.prefix"), SysCasInstance.QrOauth2.RelativePath)
	QrOA2Cfg = oauth2.Config{Scopes: []string{"admin"}, RedirectURL: qrRedirectURL}
	return func(dol *Dolphin) {
		mgr := manage.NewDefaultManager()
		mgr.SetAuthorizeCodeTokenCfg(manage.DefaultAuthorizeCodeTokenCfg)
		mgr.MapTokenStorage(dol.Manager.GetTokenStore())
		mgr.MapAccessGenerate(generates.NewAccessGenerate())
		mgr.MapClientStorage(NewClientStore())
		mgr.SetValidateURIHandler(ValidateURIHandler)

		idt := Identity{JWT: NewJsonWebToken(viper.GetString("jwt.secret"), viper.GetInt64("jwt.expire"))}
		idt.OAuth2 = server.NewServer(server.NewConfig(), mgr)
		idt.OAuth2.SetUserAuthorizationHandler(UserAuthorizationHandler)
		idt.OAuth2.SetInternalErrorHandler(func(err error) (re *errors.Response) { logrus.Error(context.TODO(), err); return })
		idt.OAuth2.SetResponseErrorHandler(func(re *errors.Response) { logrus.Error(context.TODO(), re.Error) })
		dol.Identity = &idt
		providers := []Provider{&TokenProvider{}, &JWTProvider{}, &RSAProvider{}}
		for _, p := range providers {
			dol.Identity.RegisterProvider(p)
		}
	}
}

// WithWeb defined TODO
func WithWeb() Option {
	return func(dol *Dolphin) {
		dol.Web = web.Web()
	}
}

// IsDebugging defined TODO
func IsDebugging() bool {
	return viper.GetString("app.mode") != "release"
}

// init after NewEngine
func init() {
	InitViper()
	InitLogger()
	InitCacheStore()
	InitSession()

	opts := []Option{WithWeb(), WithLifecycle(), WithManager(), WithIdentity()}
	app := NewDefault(opts...)
	StaticRoutes(app)
	MetricsRoutes(app)
	App, Run = app, app.Run
}
