apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: oauth
  name: oauth
  namespace: dolphin
binaryData:
data:
  app.properties: |-
    app.name = oauth
    app.mode = debug
    http.port = 8082
