// Code generated by dol build. Only Generate by tools if not existed.
// source: oauth2.go

package srv

import (
	"errors"
)

// Oauth2Action defined srv
func Oauth2Action(v interface{}) (interface{}, error) {
	return nil, errors.New("No implementation found")
}
