apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: platform
  namespace: dolphin
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
