// Code generated by dol build. Only Generate by tools if not existed.
// source: cache.go

package srv

import (
	"github.com/2637309949/dolphin/packages/gin"
	"github.com/2637309949/dolphin/packages/logrus"
	"github.com/2637309949/dolphin/packages/xormplus/xorm"
)

// ICacheAction defined srv
func ICacheAction(ctx *gin.Context, db *xorm.Engine, params struct{}) (interface{}, error) {
	logrus.Infoln("ICacheAction")
	return 100, nil
}
