apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: aisle
  name: aisle
  namespace: dolphin
binaryData:
data:
  app.properties: |-
    app.name = aisle
    app.mode = debug
    http.port = 8082
