// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// ActiveLessonStudent defined
type ActiveLessonStudent struct {
	//
	ALSId null.Int `xorm:"int(11) pk notnull autoincr 'a_l_s_id'" json:"a_l_s_id" xml:"a_l_s_id"`
	//
	ActiveId null.Int `xorm:"int(11) 'active_id'" json:"active_id" xml:"active_id"`
	//
	StuId null.Int `xorm:"int(11) 'stu_id'" json:"stu_id" xml:"stu_id"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" xml:"creater"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" xml:"create_date"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" xml:"updater"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" xml:"update_date"`
	//
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" xml:"isdelete"`
	//
	TlsState null.Int `xorm:"int(11) 'tls_state'" json:"tls_state" xml:"tls_state"`
	//
	SvId null.Int `xorm:"int(11) 'sv_id'" json:"sv_id" xml:"sv_id"`
	//
	IvId null.Int `xorm:"int(11) 'iv_id'" json:"iv_id" xml:"iv_id"`
}

// TableName table name of defined ActiveLessonStudent
func (m *ActiveLessonStudent) TableName() string {
	return "active_lesson_student"
}
