// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// AppError defined
type AppError struct {
	//
	AppErrorId null.Int `xorm:"int(11) pk notnull autoincr 'app_error_id'" json:"app_error_id" xml:"app_error_id"`
	//
	ErrorContent null.String `xorm:"varchar(2000) 'error_content'" json:"error_content" xml:"error_content"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" xml:"creater"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" xml:"create_date"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" xml:"updater"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" xml:"update_date"`
	//
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" xml:"isdelete"`
	//
	ErrorType null.Int `xorm:"int(11) 'error_type'" json:"error_type" xml:"error_type"`
	//
	StudentId null.Int `xorm:"int(11) 'student_id'" json:"student_id" xml:"student_id"`
	//
	PersonId null.Int `xorm:"int(11) 'person_id'" json:"person_id" xml:"person_id"`
}

// TableName table name of defined AppError
func (m *AppError) TableName() string {
	return "app_error"
}
