// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"reflect"

	"github.com/2637309949/dolphin/packages/null"
	"github.com/2637309949/dolphin/packages/xormplus/xorm"
	"github.com/2637309949/dolphin/packages/xormplus/xorm/caches"
	"github.com/2637309949/dolphin/packages/xormplus/xorm/tags"
)

// Area defined
type Area struct {
	// AreaId defined
	AreaId null.Int `xorm:"int(11) pk notnull autoincr 'area_id'" json:"area_id" form:"area_id" xml:"area_id"`
	// AreaName defined
	AreaName null.String `xorm:"varchar(20) 'area_name'" json:"area_name" form:"area_name" xml:"area_name"`
	// Creater defined
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" form:"creater" xml:"creater"`
	// CreateDate defined
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" form:"create_date" xml:"create_date"`
	// Updater defined
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" form:"updater" xml:"updater"`
	// UpdateDate defined
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" form:"update_date" xml:"update_date"`
	// Isdelete defined
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" form:"isdelete" xml:"isdelete"`
	// AreaCode defined
	AreaCode null.String `xorm:"varchar(30) 'area_code'" json:"area_code" form:"area_code" xml:"area_code"`
	// WcId defined
	WcId null.Int `xorm:"int(11) 'wc_id'" json:"wc_id" form:"wc_id" xml:"wc_id"`
}

// Parser defined
func (m *Area) Parser(db *xorm.Engine) *tags.Parser {
	return tags.NewParser("xorm", db.Dialect(), db.DB().Mapper, db.DB().Mapper, caches.NewManager())
}

// PrimaryKeys defined
func (m *Area) PrimaryKeys(db *xorm.Engine) ([]string, error) {
	v := reflect.Indirect(reflect.ValueOf(m))
	table, err := m.Parser(db).Parse(v)
	return table.PrimaryKeys, err
}

// TableName table name of defined Area
func (m *Area) TableName() string {
	return "area"
}
