// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// CcRewardUser defined
type CcRewardUser struct {
	//
	CRUId null.Int `xorm:"int(11) pk notnull autoincr 'c_r_u_id'" json:"c_r_u_id" xml:"c_r_u_id"`
	//
	UserId null.Int `xorm:"int(11) 'user_id'" json:"user_id" xml:"user_id"`
	//
	NdpdId null.Int `xorm:"int(11) 'ndpd_id'" json:"ndpd_id" xml:"ndpd_id"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" xml:"creater"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" xml:"create_date"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" xml:"updater"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" xml:"update_date"`
	//
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" xml:"isdelete"`
	//
	CcMoney null.Float `xorm:"float(10,2) 'cc_money'" json:"cc_money" xml:"cc_money"`
}

// TableName table name of defined CcRewardUser
func (m *CcRewardUser) TableName() string {
	return "cc_reward_user"
}
