// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// ClassProductCategories defined
type ClassProductCategories struct {
	//
	CPCId null.Int `xorm:"int(11) pk notnull autoincr 'c_p_c_id'" json:"c_p_c_id" xml:"c_p_c_id"`
	//
	CpcName null.String `xorm:"varchar(1000) 'cpc_name'" json:"cpc_name" xml:"cpc_name"`
	//
	CpNumberType null.Int `xorm:"int(11) 'cp_number_type'" json:"cp_number_type" xml:"cp_number_type"`
	//
	CpNumber null.Int `xorm:"int(11) 'cp_number'" json:"cp_number" xml:"cp_number"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" xml:"creater"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" xml:"create_date"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" xml:"updater"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" xml:"update_date"`
	//
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" xml:"isdelete"`
	//
	BussType null.Int `xorm:"int(11) 'buss_type'" json:"buss_type" xml:"buss_type"`
	//
	CourseId null.Int `xorm:"int(11) 'course_id'" json:"course_id" xml:"course_id"`
	//
	EnglishName null.String `xorm:"varchar(100) 'english_name'" json:"english_name" xml:"english_name"`
}

// TableName table name of defined ClassProductCategories
func (m *ClassProductCategories) TableName() string {
	return "class_product_categories"
}
