// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// ClassManageTea defined
type ClassManageTea struct {
	//
	CMTId null.Int `xorm:"int(11) pk notnull autoincr 'c_m_t_id'" json:"c_m_t_id" xml:"c_m_t_id"`
	//
	PkClass null.Int `xorm:"int(11) 'pk_class'" json:"pk_class" xml:"pk_class"`
	//
	PkTea null.Int `xorm:"int(11) 'pk_tea'" json:"pk_tea" xml:"pk_tea"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" xml:"creater"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" xml:"create_date"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" xml:"updater"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" xml:"update_date"`
	//
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" xml:"isdelete"`
	//
	PkCct null.Int `xorm:"int(11) 'pk_cct'" json:"pk_cct" xml:"pk_cct"`
}

// TableName table name of defined ClassManageTea
func (m *ClassManageTea) TableName() string {
	return "class_manage_tea"
}
