// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// CsTaskFiles defined
type CsTaskFiles struct {
	// CTFId defined
	CTFId null.Int `xorm:"int(11) pk notnull autoincr 'c_t_f_id'" json:"c_t_f_id" form:"c_t_f_id" xml:"c_t_f_id"`
	// CsTaskId defined
	CsTaskId null.Int `xorm:"int(11) 'cs_task_id'" json:"cs_task_id" form:"cs_task_id" xml:"cs_task_id"`
	// FileId defined
	FileId null.Int `xorm:"int(11) 'file_id'" json:"file_id" form:"file_id" xml:"file_id"`
	// Creater defined
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" form:"creater" xml:"creater"`
	// CreateDate defined
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" form:"create_date" xml:"create_date"`
	// Updater defined
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" form:"updater" xml:"updater"`
	// UpdateDate defined
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" form:"update_date" xml:"update_date"`
	// IsDelete defined
	IsDelete null.Int `xorm:"notnull 'is_delete'" json:"is_delete" form:"is_delete" xml:"is_delete"`
}

// TableName table name of defined CsTaskFiles
func (m *CsTaskFiles) TableName() string {
	return "cs_task_files"
}
