// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// CssHFFile defined
type CssHFFile struct {
	//
	CHFFId null.Int `xorm:"int(11) pk notnull autoincr 'c_h_f_f_id'" json:"c_h_f_f_id" xml:"c_h_f_f_id"`
	//
	Fileid null.Int `xorm:"int(11) 'fileid'" json:"fileid" xml:"fileid"`
	//
	CctId null.Int `xorm:"int(11) 'cct_id'" json:"cct_id" xml:"cct_id"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" xml:"creater"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" xml:"create_date"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" xml:"updater"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" xml:"update_date"`
	//
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" xml:"isdelete"`
	//
	ScsId null.Int `xorm:"int(11) 'scs_id'" json:"scs_id" xml:"scs_id"`
}

// TableName table name of defined CssHFFile
func (m *CssHFFile) TableName() string {
	return "css_h_f_file"
}
