// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// CssChangeKf defined
type CssChangeKf struct {
	//
	CCKId null.Int `xorm:"int(11) pk notnull autoincr 'c_c_k_id'" json:"c_c_k_id" xml:"c_c_k_id"`
	//
	PkCss null.Int `xorm:"int(11) 'pk_css'" json:"pk_css" xml:"pk_css"`
	//
	PkOldKf null.Int `xorm:"int(11) 'pk_old_kf'" json:"pk_old_kf" xml:"pk_old_kf"`
	//
	PkNewKf null.Int `xorm:"int(11) 'pk_new_kf'" json:"pk_new_kf" xml:"pk_new_kf"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" xml:"creater"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" xml:"create_date"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" xml:"updater"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" xml:"update_date"`
	//
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" xml:"isdelete"`
}

// TableName table name of defined CssChangeKf
func (m *CssChangeKf) TableName() string {
	return "css_change_kf"
}
