// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// ExamPaperProType defined
type ExamPaperProType struct {
	//
	EPPTId null.Int `xorm:"int(11) pk notnull autoincr 'e_p_p_t_id'" json:"e_p_p_t_id" xml:"e_p_p_t_id"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" xml:"create_date"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" xml:"update_date"`
	//
	EpId null.Int `xorm:"int(11) 'ep_id'" json:"ep_id" xml:"ep_id"`
	//
	PtId null.Int `xorm:"int(11) 'pt_id'" json:"pt_id" xml:"pt_id"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" xml:"creater"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" xml:"updater"`
	//
	Isdelete null.Int `xorm:"int(11) 'isdelete'" json:"isdelete" xml:"isdelete"`
}

// TableName table name of defined ExamPaperProType
func (m *ExamPaperProType) TableName() string {
	return "exam_paper_pro_type"
}
