// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// FavourableProductType defined
type FavourableProductType struct {
	//
	FPTId null.Int `xorm:"int(11) pk notnull autoincr 'f_p_t_id'" json:"f_p_t_id" xml:"f_p_t_id"`
	//
	OsId null.Int `xorm:"int(11) 'os_id'" json:"os_id" xml:"os_id"`
	//
	PtId null.Int `xorm:"int(11) 'pt_id'" json:"pt_id" xml:"pt_id"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" xml:"creater"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" xml:"create_date"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" xml:"updater"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" xml:"update_date"`
	//
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" xml:"isdelete"`
}

// TableName table name of defined FavourableProductType
func (m *FavourableProductType) TableName() string {
	return "favourable_product_type"
}
