// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// HolidaySet defined
type HolidaySet struct {
	//
	HSId null.Int `xorm:"int(11) pk notnull autoincr 'h_s_id'" json:"h_s_id" xml:"h_s_id"`
	//
	StartDate null.Time `xorm:"datetime 'start_date'" json:"start_date" xml:"start_date"`
	//
	EndDate null.Time `xorm:"datetime 'end_date'" json:"end_date" xml:"end_date"`
	//
	HolidayName null.String `xorm:"varchar(100) 'holiday_name'" json:"holiday_name" xml:"holiday_name"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" xml:"creater"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" xml:"create_date"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" xml:"updater"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" xml:"update_date"`
	//
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" xml:"isdelete"`
	//
	HisStartDate null.Time `xorm:"datetime 'his_start_date'" json:"his_start_date" xml:"his_start_date"`
	//
	HisEndDate null.Time `xorm:"datetime 'his_end_date'" json:"his_end_date" xml:"his_end_date"`
}

// TableName table name of defined HolidaySet
func (m *HolidaySet) TableName() string {
	return "holiday_set"
}
