// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"reflect"

	"github.com/2637309949/dolphin/packages/null"
	"github.com/2637309949/dolphin/packages/xormplus/xorm"
	"github.com/2637309949/dolphin/packages/xormplus/xorm/caches"
	"github.com/2637309949/dolphin/packages/xormplus/xorm/tags"
)

// KfChangeHistory defined
type KfChangeHistory struct {
	//
	KCHId null.Int `xorm:"int(11) pk notnull autoincr 'k_c_h_id'" json:"k_c_h_id" form:"k_c_h_id" xml:"k_c_h_id"`
	//
	PkSc null.Int `xorm:"int(11) 'pk_sc'" json:"pk_sc" form:"pk_sc" xml:"pk_sc"`
	//
	PkOldKf null.Int `xorm:"int(11) 'pk_old_kf'" json:"pk_old_kf" form:"pk_old_kf" xml:"pk_old_kf"`
	//
	PkNewKf null.Int `xorm:"int(11) 'pk_new_kf'" json:"pk_new_kf" form:"pk_new_kf" xml:"pk_new_kf"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" form:"creater" xml:"creater"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" form:"create_date" xml:"create_date"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" form:"updater" xml:"updater"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" form:"update_date" xml:"update_date"`
	//
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" form:"isdelete" xml:"isdelete"`
}

// Parser defined
func (m *SysCommentReply) Parser(db *xorm.Engine) *tags.Parser {
	return tags.NewParser("xorm", db.Dialect(), db.DB().Mapper, db.DB().Mapper, caches.NewManager())
}

// PrimaryKeys defined
func (m *SysCommentReply) PrimaryKeys(db *xorm.Engine) ([]string, error) {
	v := reflect.Indirect(reflect.ValueOf(m))
	table, err := m.Parser(db).Parse(v)
	return table.PrimaryKeys, err
}

// TableName table name of defined KfChangeHistory
func (m *KfChangeHistory) TableName() string {
	return "kf_change_history"
}
