// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// LevelUnit defined
type LevelUnit struct {
	//
	LevelUnitId null.Int `xorm:"int(11) pk notnull autoincr 'level_unit_id'" json:"level_unit_id" xml:"level_unit_id"`
	//
	LevelId null.Int `xorm:"int(11) 'level_id'" json:"level_id" xml:"level_id"`
	//
	UnitId null.Int `xorm:"int(11) 'unit_id'" json:"unit_id" xml:"unit_id"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" xml:"creater"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" xml:"create_date"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" xml:"updater"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" xml:"update_date"`
	//
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" xml:"isdelete"`
	//
	UnitTotalScore null.Float `xorm:"float(50,2) 'unit_total_score'" json:"unit_total_score" xml:"unit_total_score"`
}

// TableName table name of defined LevelUnit
func (m *LevelUnit) TableName() string {
	return "level_unit"
}
