// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"encoding/json"
	"reflect"

	"github.com/2637309949/dolphin/packages/null"
	"github.com/2637309949/dolphin/packages/xormplus/xorm"
	"github.com/2637309949/dolphin/packages/xormplus/xorm/caches"
	"github.com/2637309949/dolphin/packages/xormplus/xorm/tags"
)

// MarketFeeBudget defined
type MarketFeeBudget struct {
	// MFBId defined
	MFBId null.Int `xorm:"int(11) pk notnull autoincr 'm_f_b_id'" json:"m_f_b_id" form:"m_f_b_id" xml:"m_f_b_id"`
	// ProjectName defined
	ProjectName null.Int `xorm:"int(11) 'project_name'" json:"project_name" form:"project_name" xml:"project_name"`
	// Digest defined
	Digest null.String `xorm:"varchar(2000) 'digest'" json:"digest" form:"digest" xml:"digest"`
	// BudgetDetail defined
	BudgetDetail null.String `xorm:"varchar(2000) 'budget_detail'" json:"budget_detail" form:"budget_detail" xml:"budget_detail"`
	// BgdgetMoney defined
	BgdgetMoney null.Float `xorm:"float(10,2) 'bgdget_money'" json:"bgdget_money" form:"bgdget_money" xml:"bgdget_money"`
	// Remake defined
	Remake null.String `xorm:"varchar(2000) 'remake'" json:"remake" form:"remake" xml:"remake"`
	// Xgygout defined
	Xgygout null.Float `xorm:"float(10,2) 'xgygout'" json:"xgygout" form:"xgygout" xml:"xgygout"`
	// Xgygin defined
	Xgygin null.Float `xorm:"float(10,2) 'xgygin'" json:"xgygin" form:"xgygin" xml:"xgygin"`
	// Xgygbmr defined
	Xgygbmr null.Float `xorm:"float(10,2) 'xgygbmr'" json:"xgygbmr" form:"xgygbmr" xml:"xgygbmr"`
	// BudgetDate defined
	BudgetDate null.Time `xorm:"datetime 'budget_date'" json:"budget_date" form:"budget_date" xml:"budget_date"`
	// Creater defined
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" form:"creater" xml:"creater"`
	// CreateDate defined
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" form:"create_date" xml:"create_date"`
	// Updater defined
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" form:"updater" xml:"updater"`
	// UpdateDate defined
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" form:"update_date" xml:"update_date"`
	// Isdelete defined
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" form:"isdelete" xml:"isdelete"`
	// BudgetSchool defined
	BudgetSchool null.Int `xorm:"int(11) 'budget_school'" json:"budget_school" form:"budget_school" xml:"budget_school"`
	// ProName defined
	ProName null.Int `xorm:"int(11) 'pro_name'" json:"pro_name" form:"pro_name" xml:"pro_name"`
	// UserId defined
	UserId null.Int `xorm:"int(11) 'user_id'" json:"user_id" form:"user_id" xml:"user_id"`
	// BeginMonth defined
	BeginMonth null.Time `xorm:"datetime 'begin_month'" json:"begin_month" form:"begin_month" xml:"begin_month"`
	// EndMonth defined
	EndMonth null.Time `xorm:"datetime 'end_month'" json:"end_month" form:"end_month" xml:"end_month"`
	// Xgygmoney defined
	Xgygmoney null.Float `xorm:"float(10,2) 'xgygmoney'" json:"xgygmoney" form:"xgygmoney" xml:"xgygmoney"`
	// MfbCity defined
	MfbCity null.Int `xorm:"int(11) 'mfb_city'" json:"mfb_city" form:"mfb_city" xml:"mfb_city"`
}

// Marshal defined
func (m *MarketFeeBudget) Marshal() ([]byte, error) {
	return json.Marshal(m)
}

// Unmarshal defined
func (m *MarketFeeBudget) Unmarshal(data []byte) error {
	return json.Unmarshal(data, m)
}

// Parser defined
func (m *MarketFeeBudget) Parser(db *xorm.Engine) *tags.Parser {
	return tags.NewParser("xorm", db.Dialect(), db.DB().Mapper, db.DB().Mapper, caches.NewManager())
}

// PrimaryKeys defined
func (m *MarketFeeBudget) PrimaryKeys(db *xorm.Engine) ([]string, error) {
	v := reflect.Indirect(reflect.ValueOf(m))
	table, err := m.Parser(db).Parse(v)
	return table.PrimaryKeys, err
}

// TableName table name of defined MarketFeeBudget
func (m *MarketFeeBudget) TableName() string {
	return "market_fee_budget"
}
