// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// MaterialApply defined
type MaterialApply struct {
	//
	MAId null.Int `xorm:"int(11) pk notnull autoincr 'm_a_id'" json:"m_a_id" xml:"m_a_id"`
	//
	MtId null.Int `xorm:"int(11) 'mt_id'" json:"mt_id" xml:"mt_id"`
	//
	MaNum null.Float `xorm:"float(10,2) 'ma_num'" json:"ma_num" xml:"ma_num"`
	//
	MaMoney null.Float `xorm:"float(10,2) 'ma_money'" json:"ma_money" xml:"ma_money"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" xml:"creater"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" xml:"create_date"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" xml:"updater"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" xml:"update_date"`
	//
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" xml:"isdelete"`
	//
	MbId null.Int `xorm:"int(11) 'mb_id'" json:"mb_id" xml:"mb_id"`
}

// TableName table name of defined MaterialApply
func (m *MaterialApply) TableName() string {
	return "material_apply"
}
