// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// OrganSchoolBussType defined
type OrganSchoolBussType struct {
	//
	OSBTId null.Int `xorm:"int(11) pk notnull autoincr 'o_s_b_t_id'" json:"o_s_b_t_id" xml:"o_s_b_t_id"`
	//
	OsId null.Int `xorm:"int(11) 'os_id'" json:"os_id" xml:"os_id"`
	//
	OsBussType null.Int `xorm:"int(11) 'os_buss_type'" json:"os_buss_type" xml:"os_buss_type"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" xml:"creater"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" xml:"create_date"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" xml:"updater"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" xml:"update_date"`
	//
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" xml:"isdelete"`
}

// TableName table name of defined OrganSchoolBussType
func (m *OrganSchoolBussType) TableName() string {
	return "organ_school_buss_type"
}
