// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// ParticipantEvaluateInfo defined
type ParticipantEvaluateInfo struct {
	//
	PEIId null.Int `xorm:"int(11) pk notnull autoincr 'p_e_i_id'" json:"p_e_i_id" xml:"p_e_i_id"`
	//
	PtiId null.Int `xorm:"int(11) 'pti_id'" json:"pti_id" xml:"pti_id"`
	//
	Remark null.String `xorm:"varchar(2000) 'remark'" json:"remark" xml:"remark"`
	//
	TpeId null.Int `xorm:"int(11) 'tpe_id'" json:"tpe_id" xml:"tpe_id"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" xml:"creater"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" xml:"create_date"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" xml:"updater"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" xml:"update_date"`
	//
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" xml:"isdelete"`
}

// TableName table name of defined ParticipantEvaluateInfo
func (m *ParticipantEvaluateInfo) TableName() string {
	return "participant_evaluate_info"
}
