// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// ProductType defined
type ProductType struct {
	//
	PTId null.Int `xorm:"int(11) pk notnull autoincr 'p_t_id'" json:"p_t_id" xml:"p_t_id"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" xml:"create_date"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" xml:"update_date"`
	//
	PtName null.String `xorm:"varchar(50) 'pt_name'" json:"pt_name" xml:"pt_name"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" xml:"creater"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" xml:"updater"`
	//
	BusinessType null.Int `xorm:"int(11) 'business_type'" json:"business_type" xml:"business_type"`
	//
	ParentId null.Int `xorm:"int(11) 'parent_id'" json:"parent_id" xml:"parent_id"`
	//
	Isdelete null.Int `xorm:"int(11) 'isdelete'" json:"isdelete" xml:"isdelete"`
}

// TableName table name of defined ProductType
func (m *ProductType) TableName() string {
	return "product_type"
}
