// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"reflect"

	"github.com/2637309949/dolphin/packages/null"
	"github.com/2637309949/dolphin/packages/xormplus/xorm"
	"github.com/2637309949/dolphin/packages/xormplus/xorm/caches"
	"github.com/2637309949/dolphin/packages/xormplus/xorm/tags"
)

// StuClassFeedbacFile defined
type StuClassFeedbacFile struct {
	//
	SCFFId null.Int `xorm:"int(11) pk notnull autoincr 's_c_f_f_id'" json:"s_c_f_f_id" form:"s_c_f_f_id" xml:"s_c_f_f_id"`
	//
	CssCFId null.Int `xorm:"int(11) 'css_c_f_id'" json:"css_c_f_id" form:"css_c_f_id" xml:"css_c_f_id"`
	//
	FileId null.Int `xorm:"int(11) 'file_id'" json:"file_id" form:"file_id" xml:"file_id"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" form:"creater" xml:"creater"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" form:"create_date" xml:"create_date"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" form:"updater" xml:"updater"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" form:"update_date" xml:"update_date"`
	//
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" form:"isdelete" xml:"isdelete"`
	//
	CfId null.Int `xorm:"int(11) 'cf_id'" json:"cf_id" form:"cf_id" xml:"cf_id"`
	//
	CsId null.Int `xorm:"int(11) 'cs_id'" json:"cs_id" form:"cs_id" xml:"cs_id"`
	//
	CcsId null.Int `xorm:"int(11) 'ccs_id'" json:"ccs_id" form:"ccs_id" xml:"ccs_id"`
}

// Parser defined
func (m *StuClassFeedbacFile) Parser(db *xorm.Engine) *tags.Parser {
	return tags.NewParser("xorm", db.Dialect(), db.DB().Mapper, db.DB().Mapper, caches.NewManager())
}

// PrimaryKeys defined
func (m *StuClassFeedbacFile) PrimaryKeys(db *xorm.Engine) ([]string, error) {
	v := reflect.Indirect(reflect.ValueOf(m))
	table, err := m.Parser(db).Parse(v)
	return table.PrimaryKeys, err
}

// TableName table name of defined StuClassFeedbacFile
func (m *StuClassFeedbacFile) TableName() string {
	return "stu_class_feedbac_file"
}
