// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// StuCourseVideo defined
type StuCourseVideo struct {
	//
	SCVId null.Int `xorm:"int(11) pk notnull autoincr 's_c_v_id'" json:"s_c_v_id" xml:"s_c_v_id"`
	//
	CssId null.Int `xorm:"int(11) 'css_id'" json:"css_id" xml:"css_id"`
	//
	CvId null.Int `xorm:"int(11) 'cv_id'" json:"cv_id" xml:"cv_id"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" xml:"creater"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" xml:"create_date"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" xml:"updater"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" xml:"update_date"`
	//
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" xml:"isdelete"`
	//
	ScsId null.Int `xorm:"int(11) 'scs_id'" json:"scs_id" xml:"scs_id"`
}

// TableName table name of defined StuCourseVideo
func (m *StuCourseVideo) TableName() string {
	return "stu_course_video"
}
