// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// StuClassTypeAssBook defined
type StuClassTypeAssBook struct {
	//
	SCTABId null.Int `xorm:"int(11) pk notnull autoincr 's_c_t_a_b_id'" json:"s_c_t_a_b_id" xml:"s_c_t_a_b_id"`
	//
	SctId null.Int `xorm:"int(11) 'sct_id'" json:"sct_id" xml:"sct_id"`
	//
	AbId null.Int `xorm:"int(11) 'ab_id'" json:"ab_id" xml:"ab_id"`
	//
	AbSource null.Int `xorm:"int(11) 'ab_source'" json:"ab_source" xml:"ab_source"`
	//
	AbPrice null.Float `xorm:"float(10,2) 'ab_price'" json:"ab_price" xml:"ab_price"`
	//
	IfReceive null.Int `xorm:"int(11) 'if_receive'" json:"if_receive" xml:"if_receive"`
	//
	RefPrice null.Float `xorm:"float(10,2) 'ref_price'" json:"ref_price" xml:"ref_price"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" xml:"creater"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" xml:"create_date"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" xml:"updater"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" xml:"update_date"`
	//
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" xml:"isdelete"`
	//
	RefMoeny null.Float `xorm:"float(10,2) 'ref_moeny'" json:"ref_moeny" xml:"ref_moeny"`
	//
	BuyNum null.Float `xorm:"float(10,2) 'buy_num'" json:"buy_num" xml:"buy_num"`
	//
	OfId null.Int `xorm:"int(11) 'of_id'" json:"of_id" xml:"of_id"`
}

// TableName table name of defined StuClassTypeAssBook
func (m *StuClassTypeAssBook) TableName() string {
	return "stu_class_type_ass_book"
}
