// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// StuClassFeedback defined
type StuClassFeedback struct {
	// SCFId defined
	SCFId null.Int `xorm:"int(11) pk notnull autoincr 's_c_f_id'" json:"s_c_f_id" form:"s_c_f_id" xml:"s_c_f_id"`
	// CfContent defined
	CfContent null.String `xorm:"'cf_content'" json:"cf_content" form:"cf_content" xml:"cf_content"`
	// CfId defined
	CfId null.Int `xorm:"int(11) 'cf_id'" json:"cf_id" form:"cf_id" xml:"cf_id"`
	// CssId defined
	CssId null.Int `xorm:"int(11) 'css_id'" json:"css_id" form:"css_id" xml:"css_id"`
	// Hear defined
	Hear null.Int `xorm:"int(11) 'hear'" json:"hear" form:"hear" xml:"hear"`
	// Say defined
	Say null.Int `xorm:"int(11) 'say'" json:"say" form:"say" xml:"say"`
	// CfRead defined
	CfRead null.Int `xorm:"int(11) 'cf_read'" json:"cf_read" form:"cf_read" xml:"cf_read"`
	// CfWrite defined
	CfWrite null.Int `xorm:"int(11) 'cf_write'" json:"cf_write" form:"cf_write" xml:"cf_write"`
	// CfZhnl defined
	CfZhnl null.Int `xorm:"int(11) 'cf_zhnl'" json:"cf_zhnl" form:"cf_zhnl" xml:"cf_zhnl"`
	// Creater defined
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" form:"creater" xml:"creater"`
	// CreateDate defined
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" form:"create_date" xml:"create_date"`
	// Updater defined
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" form:"updater" xml:"updater"`
	// UpdateDate defined
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" form:"update_date" xml:"update_date"`
	// IsDelete defined
	IsDelete null.Int `xorm:"notnull 'is_delete'" json:"is_delete" form:"is_delete" xml:"is_delete"`
	// ScsId defined
	ScsId null.Int `xorm:"int(11) 'scs_id'" json:"scs_id" form:"scs_id" xml:"scs_id"`
	// See defined
	See null.Int `xorm:"int(11) 'see'" json:"see" form:"see" xml:"see"`
}

// TableName table name of defined StuClassFeedback
func (m *StuClassFeedback) TableName() string {
	return "stu_class_feedback"
}
