// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// StudentCzIntegral defined
type StudentCzIntegral struct {
	//
	SCIId null.Int `xorm:"int(11) pk notnull autoincr 's_c_i_id'" json:"s_c_i_id" xml:"s_c_i_id"`
	//
	StuId null.Int `xorm:"int(11) 'stu_id'" json:"stu_id" xml:"stu_id"`
	//
	Integral null.Float `xorm:"float(50,2) 'integral'" json:"integral" xml:"integral"`
	//
	IntegralDesc null.String `xorm:"varchar(500) 'integral_desc'" json:"integral_desc" xml:"integral_desc"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" xml:"creater"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" xml:"create_date"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" xml:"updater"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" xml:"update_date"`
	//
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" xml:"isdelete"`
	//
	IntegralState null.Int `xorm:"int(11) 'integral_state'" json:"integral_state" xml:"integral_state"`
	//
	JfOrder null.Int `xorm:"int(11) 'jf_order'" json:"jf_order" xml:"jf_order"`
	//
	YhjfOrderid null.Int `xorm:"int(11) 'yhjf_orderid'" json:"yhjf_orderid" xml:"yhjf_orderid"`
	//
	SctId null.Int `xorm:"int(11) 'sct_id'" json:"sct_id" xml:"sct_id"`
}

// TableName table name of defined StudentCzIntegral
func (m *StudentCzIntegral) TableName() string {
	return "student_cz_integral"
}
