// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// StudentReopened defined
type StudentReopened struct {
	//
	SRId null.Int `xorm:"int(11) pk notnull autoincr 's_r_id'" json:"s_r_id" xml:"s_r_id"`
	//
	StuRemark null.String `xorm:"varchar(2000) 'stu_remark'" json:"stu_remark" xml:"stu_remark"`
	//
	UserId null.Int `xorm:"int(11) 'user_id'" json:"user_id" xml:"user_id"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" xml:"creater"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" xml:"create_date"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" xml:"updater"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" xml:"update_date"`
	//
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" xml:"isdelete"`
	//
	StrId null.Int `xorm:"int(11) 'str_id'" json:"str_id" xml:"str_id"`
}

// TableName table name of defined StudentReopened
func (m *StudentReopened) TableName() string {
	return "student_reopened"
}
