// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"encoding/json"
	"reflect"

	"github.com/2637309949/dolphin/packages/null"
	"github.com/2637309949/dolphin/packages/xormplus/xorm"
	"github.com/2637309949/dolphin/packages/xormplus/xorm/caches"
	"github.com/2637309949/dolphin/packages/xormplus/xorm/tags"
)

// StudentRzIntegral defined
type StudentRzIntegral struct {
	// SRIId defined
	SRIId null.Int `xorm:"int(11) pk notnull autoincr 's_r_i_id'" json:"s_r_i_id" form:"s_r_i_id" xml:"s_r_i_id"`
	// StuId defined
	StuId null.Int `xorm:"int(11) 'stu_id'" json:"stu_id" form:"stu_id" xml:"stu_id"`
	// Integral defined
	Integral null.Float `xorm:"float(10,2) 'integral'" json:"integral" form:"integral" xml:"integral"`
	// IntegralSource defined
	IntegralSource null.Int `xorm:"int(11) 'integral_source'" json:"integral_source" form:"integral_source" xml:"integral_source"`
	// Creater defined
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" form:"creater" xml:"creater"`
	// CreateDate defined
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" form:"create_date" xml:"create_date"`
	// Updater defined
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" form:"updater" xml:"updater"`
	// UpdateDate defined
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" form:"update_date" xml:"update_date"`
	// Isdelete defined
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" form:"isdelete" xml:"isdelete"`
	// IntegralDesc defined
	IntegralDesc null.String `xorm:"varchar(500) 'integral_desc'" json:"integral_desc" form:"integral_desc" xml:"integral_desc"`
	// IntegralState defined
	IntegralState null.Int `xorm:"int(11) 'integral_state'" json:"integral_state" form:"integral_state" xml:"integral_state"`
	// TlsId defined
	TlsId null.Int `xorm:"int(11) 'tls_id'" json:"tls_id" form:"tls_id" xml:"tls_id"`
	// BuyOrderid defined
	BuyOrderid null.Int `xorm:"int(11) 'buy_orderid'" json:"buy_orderid" form:"buy_orderid" xml:"buy_orderid"`
	// LtorderId defined
	LtorderId null.Int `xorm:"int(11) 'ltorder_id'" json:"ltorder_id" form:"ltorder_id" xml:"ltorder_id"`
	// FeeId defined
	FeeId null.Int `xorm:"int(11) 'fee_id'" json:"fee_id" form:"fee_id" xml:"fee_id"`
	// PkOdd defined
	PkOdd null.Int `xorm:"int(11) 'pk_odd'" json:"pk_odd" form:"pk_odd" xml:"pk_odd"`
}

// Marshal defined
func (m *StudentRzIntegral) Marshal() ([]byte, error) {
	return json.Marshal(m)
}

// Unmarshal defined
func (m *StudentRzIntegral) Unmarshal(data []byte) error {
	return json.Unmarshal(data, m)
}

// ToMap defined
func (m *StudentRzIntegral) ToMap() (map[string]interface{}, error) {
	byt, err := m.Marshal()
	if err != nil {
		return nil, err
	}
	itf := map[string]interface{}{}
	err = json.Unmarshal(byt, &itf)
	return itf, err
}

// FromMap defined
func (m *StudentRzIntegral) FromMap(fm map[string]interface{}) error {
	byt, err := json.Marshal(fm)
	if err != nil {
		return err
	}
	err = m.Unmarshal(byt)
	return err
}

// Parser defined
func (m *StudentRzIntegral) Parser(db *xorm.Engine) *tags.Parser {
	return tags.NewParser("xorm", db.Dialect(), db.DB().Mapper, db.DB().Mapper, caches.NewManager())
}

// PrimaryKeys defined
func (m *StudentRzIntegral) PrimaryKeys(db *xorm.Engine) ([]string, error) {
	v := reflect.Indirect(reflect.ValueOf(m))
	table, err := m.Parser(db).Parse(v)
	return table.PrimaryKeys, err
}

// TableName table name of defined StudentRzIntegral
func (m *StudentRzIntegral) TableName() string {
	return "student_rz_integral"
}
