// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// TempStu defined
type TempStu struct {
	//
	Fid null.Int `xorm:"int(11) pk notnull 'fid'" json:"fid" xml:"fid"`
	//
	StuName null.String `xorm:"varchar(255) 'stu_name'" json:"stu_name" xml:"stu_name"`
	//
	StuPhone null.String `xorm:"varchar(255) 'stu_phone'" json:"stu_phone" xml:"stu_phone"`
}

// TableName table name of defined TempStu
func (m *TempStu) TableName() string {
	return "temp_stu"
}
