// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// TempStorageRz defined
type TempStorageRz struct {
	//
	TSRId null.Int `xorm:"int(11) pk notnull autoincr 't_s_r_id'" json:"t_s_r_id" xml:"t_s_r_id"`
	//
	StuId null.Int `xorm:"int(11) 'stu_id'" json:"stu_id" xml:"stu_id"`
	//
	TollMoney null.Float `xorm:"float(11,2) 'toll_money'" json:"toll_money" xml:"toll_money"`
	//
	FeeWay null.Int `xorm:"int(11) 'fee_way'" json:"fee_way" xml:"fee_way"`
	//
	ComeEnter null.Int `xorm:"int(11) 'come_enter'" json:"come_enter" xml:"come_enter"`
	//
	TollDate null.Time `xorm:"datetime 'toll_date'" json:"toll_date" xml:"toll_date"`
	//
	Remark null.String `xorm:"varchar(500) 'remark'" json:"remark" xml:"remark"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" xml:"creater"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" xml:"create_date"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" xml:"updater"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" xml:"update_date"`
	//
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" xml:"isdelete"`
	//
	TsrStuId null.Int `xorm:"int(11) 'tsr_stu_id'" json:"tsr_stu_id" xml:"tsr_stu_id"`
	//
	RefId null.Int `xorm:"int(11) 'ref_id'" json:"ref_id" xml:"ref_id"`
	//
	ZcSource null.Int `xorm:"int(11) 'zc_source'" json:"zc_source" xml:"zc_source"`
	//
	BussType null.Int `xorm:"int(11) 'buss_type'" json:"buss_type" xml:"buss_type"`
	//
	CheckState null.Int `xorm:"int(11) 'check_state'" json:"check_state" xml:"check_state"`
	//
	RefRzOrderid null.Int `xorm:"int(11) 'ref_rz_orderid'" json:"ref_rz_orderid" xml:"ref_rz_orderid"`
}

// TableName table name of defined TempStorageRz
func (m *TempStorageRz) TableName() string {
	return "temp_storage_rz"
}
