// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// TmLevel defined
type TmLevel struct {
	// TmLevelId defined
	TmLevelId null.Int `xorm:"int(11) pk notnull autoincr 'tm_level_id'" json:"tm_level_id" form:"tm_level_id" xml:"tm_level_id"`
	// TmId defined
	TmId null.Int `xorm:"int(11) 'tm_id'" json:"tm_id" form:"tm_id" xml:"tm_id"`
	// LevelId defined
	LevelId null.Int `xorm:"int(11) 'level_id'" json:"level_id" form:"level_id" xml:"level_id"`
	// Creater defined
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" form:"creater" xml:"creater"`
	// CreateDate defined
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" form:"create_date" xml:"create_date"`
	// Updater defined
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" form:"updater" xml:"updater"`
	// UpdateDate defined
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" form:"update_date" xml:"update_date"`
	// IsDelete defined
	IsDelete null.Int `xorm:"notnull 'is_delete'" json:"is_delete" form:"is_delete" xml:"is_delete"`
}

// TableName table name of defined TmLevel
func (m *TmLevel) TableName() string {
	return "tm_level"
}
