// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// TrainerEvaluateParticipant defined
type TrainerEvaluateParticipant struct {
	//
	TEPId null.Int `xorm:"int(11) pk notnull autoincr 't_e_p_id'" json:"t_e_p_id" xml:"t_e_p_id"`
	//
	TrainerId null.Int `xorm:"int(11) 'trainer_id'" json:"trainer_id" xml:"trainer_id"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" xml:"creater"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" xml:"create_date"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" xml:"updater"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" xml:"update_date"`
	//
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" xml:"isdelete"`
	//
	EvaluateRemark null.String `xorm:"varchar(300) 'evaluate_remark'" json:"evaluate_remark" xml:"evaluate_remark"`
}

// TableName table name of defined TrainerEvaluateParticipant
func (m *TrainerEvaluateParticipant) TableName() string {
	return "trainer_evaluate_participant"
}
