// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// UserCasting defined
type UserCasting struct {
	//
	UserCastId null.Int `xorm:"int(11) pk notnull autoincr 'user_cast_id'" json:"user_cast_id" xml:"user_cast_id"`
	//
	UserId null.Int `xorm:"int(11) 'user_id'" json:"user_id" xml:"user_id"`
	//
	CastId null.Int `xorm:"int(11) 'cast_id'" json:"cast_id" xml:"cast_id"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" xml:"creater"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" xml:"create_date"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" xml:"updater"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" xml:"update_date"`
}

// TableName table name of defined UserCasting
func (m *UserCasting) TableName() string {
	return "user_casting"
}
