// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// YbzfPos defined
type YbzfPos struct {
	// YbzfPosId defined
	YbzfPosId null.Int `xorm:"int(11) pk notnull autoincr 'ybzf_pos_id'" json:"ybzf_pos_id" form:"ybzf_pos_id" xml:"ybzf_pos_id"`
	// YbzfNumber defined
	YbzfNumber null.String `xorm:"varchar(10000) 'ybzf_number'" json:"ybzf_number" form:"ybzf_number" xml:"ybzf_number"`
	// Creater defined
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" form:"creater" xml:"creater"`
	// CreateDate defined
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" form:"create_date" xml:"create_date"`
	// Updater defined
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" form:"updater" xml:"updater"`
	// UpdateDate defined
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" form:"update_date" xml:"update_date"`
	// IsDelete defined
	IsDelete null.Int `xorm:"notnull 'is_delete'" json:"is_delete" form:"is_delete" xml:"is_delete"`
	// OnOffState defined
	OnOffState null.Int `xorm:"int(11) 'on_off_state'" json:"on_off_state" form:"on_off_state" xml:"on_off_state"`
	// YbzfDesc defined
	YbzfDesc null.String `xorm:"varchar(1000) 'ybzf_desc'" json:"ybzf_desc" form:"ybzf_desc" xml:"ybzf_desc"`
	// SchId defined
	SchId null.Int `xorm:"int(11) 'sch_id'" json:"sch_id" form:"sch_id" xml:"sch_id"`
}

// TableName table name of defined YbzfPos
func (m *YbzfPos) TableName() string {
	return "ybzf_pos"
}
