// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// ZbxzsgzValiddate defined
type ZbxzsgzValiddate struct {
	//
	ZVId null.Int `xorm:"int(11) pk notnull autoincr 'z_v_id'" json:"z_v_id" xml:"z_v_id"`
	//
	ZbxzsgzId null.Int `xorm:"int(11) 'zbxzsgz_id'" json:"zbxzsgz_id" xml:"zbxzsgz_id"`
	//
	BeginDate null.Time `xorm:"datetime 'begin_date'" json:"begin_date" xml:"begin_date"`
	//
	EndDate null.Time `xorm:"datetime 'end_date'" json:"end_date" xml:"end_date"`
	//
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" xml:"creater"`
	//
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" xml:"create_date"`
	//
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" xml:"updater"`
	//
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" xml:"update_date"`
	//
	Isdelete null.Int `xorm:"notnull 'isdelete'" json:"isdelete" xml:"isdelete"`
	//
	SyhourZsbl null.Float `xorm:"float(50,2) 'syhour_zsbl'" json:"syhour_zsbl" xml:"syhour_zsbl"`
}

// TableName table name of defined ZbxzsgzValiddate
func (m *ZbxzsgzValiddate) TableName() string {
	return "zbxzsgz_validdate"
}
