apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: dolphin
binaryData:
data:
  app.properties: |-
    app.name = kafka
    app.mode = debug
    http.port = 8082
