apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: platform
  namespace: dolphin
  labels:
    name: platform
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: platform
    spec:
      containers:
        - image: ghost
          imagePullPolicy: Always
          name: platform
          resources:
            requests:
              cpu: "20m"
              memory: "55M"
          livenessProbe:
            httpGet:
              path: /
              port: 2368
            initialDelaySeconds: 90
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 2368
            initialDelaySeconds: 30
            timeoutSeconds: 10
          ports:
            - containerPort: 2368
              name: 2368tcp02
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/ghost/content
              name: storage-platform
              subPath: ghost
      volumes:
        - name: storage-platform
          persistentVolumeClaim:
            claimName: claim-platform
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson
