// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// FlarumNotifications defined
type FlarumNotifications struct {
	//
	ID null.Int `xorm:"int(10) pk notnull autoincr 'id'" json:"id" xml:"id"`
	//
	UserId null.Int `xorm:"int(10) notnull 'user_id'" json:"user_id" xml:"user_id"`
	//
	FromUserId null.Int `xorm:"int(10) 'from_user_id'" json:"from_user_id" xml:"from_user_id"`
	//
	Type null.String `xorm:"varchar(100) notnull 'type'" json:"type" xml:"type"`
	//
	SubjectId null.Int `xorm:"int(10) 'subject_id'" json:"subject_id" xml:"subject_id"`
	//
	Data []byte `xorm:"blob 'data'" json:"data" xml:"data"`
	//
	ReadAt null.Time `xorm:"datetime 'read_at'" json:"read_at" xml:"read_at"`
	// Creator
	CreateBy null.String `xorm:"varchar(36) comment('Creator') 'create_by'" json:"create_by" xml:"create_by"`
	// Creation time
	CreateTime null.Time `xorm:"datetime comment('Creation time') 'create_time'" json:"create_time" xml:"create_time"`
	// Last updated by
	UpdateBy null.String `xorm:"varchar(36) comment('Last updated by') 'update_by'" json:"update_by" xml:"update_by"`
	// Last update time
	UpdateTime null.Time `xorm:"datetime comment('Last update time') 'update_time'" json:"update_time" xml:"update_time"`
	// Delete tag
	DelFlag null.Int `xorm:"notnull comment('Delete tag') 'del_flag'" json:"del_flag" xml:"del_flag"`
	// Remark
	Remark null.String `xorm:"varchar(200) comment('Remark') 'remark'" json:"remark" xml:"remark"`
}

// TableName table name of defined FlarumNotifications
func (m *FlarumNotifications) TableName() string {
	return "flarum_notifications"
}
