apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{.Name}}
  name: {{.Name}}
  namespace: dolphin
binaryData:
data:
  app.properties: |-
    app.name = {{.Name}}
    app.mode = debug
    http.port = 8082
