// Code generated by dol build. Only Generate by tools if not existed.
// source: vote.go

package api

import (
	"scene/types"

	"github.com/2637309949/dolphin/packages/logrus"
	"github.com/2637309949/dolphin/packages/null"
)

// VoteLike api implementation
// @Summary like article
// @Tags vote controller
// @Accept application/json
// @Param Authorization header string false "认证令牌"
// @Param id body types.VoteInfo false "like id"
// @Produce application/json
// @Failure 403 {object} types.Fail
// @Success 200 {object} types.Success
// @Failure 500 {object} types.Fail
// @Router /api/vote/like [post]
func (ctr *Vote) VoteLike(ctx *Context) {
	var payload types.VoteInfo
	if err := ctx.ShouldBindWith(&payload); err != nil {
		logrus.Error(ctx, err)
		ctx.Fail(err)
		return
	}
	payload.UserId = null.StringFrom(ctx.MustToken().GetUserID())

	db := ctx.MustDB()
	ret, err := ctr.Srv.Like(ctx, db, payload)
	if err != nil {
		logrus.Error(ctx, err)
		ctx.Fail(err)
		return
	}
	ctx.Success(ret)
}
