// Code generated by dol build. Only Generate by tools if not existed.
// source: xlsx.go

package api

import (
	"errors"
	"strings"

	"github.com/sirupsen/logrus"
)

// XlsxImport api implementation
// @Summary import xlsx
// @Tags xlsx controller
// @Accept application/json
// @Produce application/json
// @Param Authorization header string false "认证令牌"
// @Failure 403 {object} types.Fail
// @Success 200 {object} types.Success
// @Failure 500 {object} types.Fail
// @Router /api/xlsx/import [post]
func (ctr *Xlsx) XlsxImport(ctx *Context) {
	var payload struct{}
	if err := ctx.ShouldBindWith(&payload); err != nil {
		logrus.Error(err)
		ctx.Fail(err)
		return
	}

	var err error
	file, headers, _ := ctx.Request.FormFile("file")
	defer file.Close()

	isXlsx := strings.Index(headers.Filename, ".xlsx")
	if isXlsx == -1 {
		ctx.Fail(errors.New("上传格式必须是xlsx格式"))
		return
	}

	sheet, err := ctr.Srv.ParseExcel(file, 1)
	if err != nil {
		logrus.Error(err)
		ctx.Fail(err)
		return
	}
	ctx.Success(sheet)
}
