// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package types

import (
	"encoding/json"

	"github.com/2637309949/dolphin/packages/null"
)

// BranchCompany defined
type BranchCompany struct {
	// BCId defined
	BCId null.Int `xorm:"int(11) pk notnull autoincr 'b_c_id'" json:"b_c_id" form:"b_c_id" xml:"b_c_id"`
	// CompanyName defined
	CompanyName null.String `xorm:"varchar(1000) 'company_name'" json:"company_name" form:"company_name" xml:"company_name"`
	// Creater defined
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" form:"creater" xml:"creater"`
	// CreateDate defined
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" form:"create_date" xml:"create_date"`
	// Updater defined
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" form:"updater" xml:"updater"`
	// UpdateDate defined
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" form:"update_date" xml:"update_date"`
	// IsDelete defined
	IsDelete null.Int `xorm:"notnull 'is_delete'" json:"is_delete" form:"is_delete" xml:"is_delete"`
	// BcIndex defined
	BcIndex null.Int `xorm:"int(11) 'bc_index'" json:"bc_index" form:"bc_index" xml:"bc_index"`
	// Onoff defined
	Onoff null.Int `xorm:"int(11) 'onoff'" json:"onoff" form:"onoff" xml:"onoff"`
}

// TableName table name of defined BranchCompany
func (m *BranchCompany) TableName() string {
	return "branch_company"
}

func (r *BranchCompany) Marshal() ([]byte, error) {
	return json.Marshal(r)
}

func UnmarshalBranchCompany(data []byte) (BranchCompany, error) {
	var r BranchCompany
	err := json.Unmarshal(data, &r)
	return r, err
}
