// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package types

import (
	"encoding/json"

	"github.com/2637309949/dolphin/packages/null"
)

// ClassChangeTeaNew defined
type ClassChangeTeaNew struct {
	// CCTNId defined
	CCTNId null.Int `xorm:"int(11) pk notnull autoincr 'c_c_t_n_id'" json:"c_c_t_n_id" form:"c_c_t_n_id" xml:"c_c_t_n_id"`
	// PkCct defined
	PkCct null.Int `xorm:"int(11) 'pk_cct'" json:"pk_cct" form:"pk_cct" xml:"pk_cct"`
	// PkNewTea defined
	PkNewTea null.Int `xorm:"int(11) 'pk_new_tea'" json:"pk_new_tea" form:"pk_new_tea" xml:"pk_new_tea"`
	// Creater defined
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" form:"creater" xml:"creater"`
	// CreateDate defined
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" form:"create_date" xml:"create_date"`
	// Updater defined
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" form:"updater" xml:"updater"`
	// UpdateDate defined
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" form:"update_date" xml:"update_date"`
	// IsDelete defined
	IsDelete null.Int `xorm:"notnull 'is_delete'" json:"is_delete" form:"is_delete" xml:"is_delete"`
}

// TableName table name of defined ClassChangeTeaNew
func (m *ClassChangeTeaNew) TableName() string {
	return "class_change_tea_new"
}

func (r *ClassChangeTeaNew) Marshal() ([]byte, error) {
	return json.Marshal(r)
}

func UnmarshalClassChangeTeaNew(data []byte) (ClassChangeTeaNew, error) {
	var r ClassChangeTeaNew
	err := json.Unmarshal(data, &r)
	return r, err
}
