// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package types

import (
	"github.com/2637309949/dolphin/packages/null"
)

// RegularDictionary defined
type RegularDictionary struct {
	// PkDicId defined
	PkDicId null.Int `xorm:"int(11) pk notnull autoincr 'pk_dic_id'" json:"pk_dic_id" form:"pk_dic_id" xml:"pk_dic_id"`
	// RegularDicId defined
	RegularDicId null.Float `xorm:"float(11,2) 'regular_dic_id'" json:"regular_dic_id" form:"regular_dic_id" xml:"regular_dic_id"`
	// DicParent defined
	DicParent null.Float `xorm:"float(11,2) 'dic_parent'" json:"dic_parent" form:"dic_parent" xml:"dic_parent"`
	// DicId defined
	DicId null.Float `xorm:"float(11,2) 'dic_id'" json:"dic_id" form:"dic_id" xml:"dic_id"`
	// DicName defined
	DicName null.String `xorm:"varchar(500) 'dic_name'" json:"dic_name" form:"dic_name" xml:"dic_name"`
	// Creater defined
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" form:"creater" xml:"creater"`
	// CreateDate defined
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" form:"create_date" xml:"create_date"`
	// Updater defined
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" form:"updater" xml:"updater"`
	// UpdateDate defined
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" form:"update_date" xml:"update_date"`
}

// TableName table name of defined RegularDictionary
func (m *RegularDictionary) TableName() string {
	return "regular_dictionary"
}
