// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package types

import (
	"github.com/2637309949/dolphin/packages/null"
)

// SchMarketPlan defined
type SchMarketPlan struct {
	// SMPId defined
	SMPId null.Int `xorm:"int(11) pk notnull autoincr 's_m_p_id'" json:"s_m_p_id" form:"s_m_p_id" xml:"s_m_p_id"`
	// OsId defined
	OsId null.Int `xorm:"int(11) 'os_id'" json:"os_id" form:"os_id" xml:"os_id"`
	// PlanMonth defined
	PlanMonth null.Time `xorm:"datetime 'plan_month'" json:"plan_month" form:"plan_month" xml:"plan_month"`
	// InPlan defined
	InPlan null.Float `xorm:"float(11,2) 'in_plan'" json:"in_plan" form:"in_plan" xml:"in_plan"`
	// OutPlan defined
	OutPlan null.Float `xorm:"float(11,2) 'out_plan'" json:"out_plan" form:"out_plan" xml:"out_plan"`
	// DemoPlan defined
	DemoPlan null.Float `xorm:"float(11,2) 'demo_plan'" json:"demo_plan" form:"demo_plan" xml:"demo_plan"`
	// AchievementPlan defined
	AchievementPlan null.Float `xorm:"float(11,2) 'achievement_plan'" json:"achievement_plan" form:"achievement_plan" xml:"achievement_plan"`
	// Creater defined
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" form:"creater" xml:"creater"`
	// CreateDate defined
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" form:"create_date" xml:"create_date"`
	// Updater defined
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" form:"updater" xml:"updater"`
	// UpdateDate defined
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" form:"update_date" xml:"update_date"`
	// IsDelete defined
	IsDelete null.Int `xorm:"notnull 'is_delete'" json:"is_delete" form:"is_delete" xml:"is_delete"`
}

// TableName table name of defined SchMarketPlan
func (m *SchMarketPlan) TableName() string {
	return "sch_market_plan"
}
