// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package types

import (
	"encoding/json"

	"github.com/2637309949/dolphin/packages/null"
)

// TempStu defined
type TempStu struct {
	// Fid defined
	Fid null.Int `xorm:"int(11) pk notnull 'fid'" json:"fid" form:"fid" xml:"fid"`
	// StuName defined
	StuName null.String `xorm:"varchar(255) 'stu_name'" json:"stu_name" form:"stu_name" xml:"stu_name"`
	// StuPhone defined
	StuPhone null.String `xorm:"varchar(255) 'stu_phone'" json:"stu_phone" form:"stu_phone" xml:"stu_phone"`
}

// TableName table name of defined TempStu
func (m *TempStu) TableName() string {
	return "temp_stu"
}

func (r *TempStu) Marshal() ([]byte, error) {
	return json.Marshal(r)
}

func UnmarshalTempStu(data []byte) (TempStu, error) {
	var r TempStu
	err := json.Unmarshal(data, &r)
	return r, err
}
