// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package types

import (
	"encoding/json"

	"github.com/2637309949/dolphin/packages/null"
)

// TextBookProductType defined
type TextBookProductType struct {
	// TBPTId defined
	TBPTId null.Int `xorm:"int(11) pk notnull autoincr 't_b_p_t_id'" json:"t_b_p_t_id" form:"t_b_p_t_id" xml:"t_b_p_t_id"`
	// TbId defined
	TbId null.Int `xorm:"int(11) 'tb_id'" json:"tb_id" form:"tb_id" xml:"tb_id"`
	// PtId defined
	PtId null.Int `xorm:"int(11) 'pt_id'" json:"pt_id" form:"pt_id" xml:"pt_id"`
	// Creater defined
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" form:"creater" xml:"creater"`
	// CreateDate defined
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" form:"create_date" xml:"create_date"`
	// Updater defined
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" form:"updater" xml:"updater"`
	// UpdateDate defined
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" form:"update_date" xml:"update_date"`
	// IsDelete defined
	IsDelete null.Int `xorm:"int(11) 'is_delete'" json:"is_delete" form:"is_delete" xml:"is_delete"`
}

// TableName table name of defined TextBookProductType
func (m *TextBookProductType) TableName() string {
	return "text_book_product_type"
}

func (r *TextBookProductType) Marshal() ([]byte, error) {
	return json.Marshal(r)
}

func UnmarshalTextBookProductType(data []byte) (TextBookProductType, error) {
	var r TextBookProductType
	err := json.Unmarshal(data, &r)
	return r, err
}
