// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package types

import (
	"encoding/json"

	"github.com/2637309949/dolphin/packages/null"
)

// TrainerEvaluateParticipant defined
type TrainerEvaluateParticipant struct {
	// TEPId defined
	TEPId null.Int `xorm:"int(11) pk notnull autoincr 't_e_p_id'" json:"t_e_p_id" form:"t_e_p_id" xml:"t_e_p_id"`
	// TrainerId defined
	TrainerId null.Int `xorm:"int(11) 'trainer_id'" json:"trainer_id" form:"trainer_id" xml:"trainer_id"`
	// Creater defined
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" form:"creater" xml:"creater"`
	// CreateDate defined
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" form:"create_date" xml:"create_date"`
	// Updater defined
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" form:"updater" xml:"updater"`
	// UpdateDate defined
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" form:"update_date" xml:"update_date"`
	// IsDelete defined
	IsDelete null.Int `xorm:"notnull 'is_delete'" json:"is_delete" form:"is_delete" xml:"is_delete"`
	// EvaluateRemark defined
	EvaluateRemark null.String `xorm:"varchar(300) 'evaluate_remark'" json:"evaluate_remark" form:"evaluate_remark" xml:"evaluate_remark"`
}

// TableName table name of defined TrainerEvaluateParticipant
func (m *TrainerEvaluateParticipant) TableName() string {
	return "trainer_evaluate_participant"
}

func (r *TrainerEvaluateParticipant) Marshal() ([]byte, error) {
	return json.Marshal(r)
}

func UnmarshalTrainerEvaluateParticipant(data []byte) (TrainerEvaluateParticipant, error) {
	var r TrainerEvaluateParticipant
	err := json.Unmarshal(data, &r)
	return r, err
}
