// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package types

import (
	"encoding/json"

	"github.com/2637309949/dolphin/packages/null"
)

// WastageFollowupRecord defined
type WastageFollowupRecord struct {
	// WFRId defined
	WFRId null.Int `xorm:"int(11) pk notnull autoincr 'w_f_r_id'" json:"w_f_r_id" form:"w_f_r_id" xml:"w_f_r_id"`
	// EnglishLevel defined
	EnglishLevel null.String `xorm:"varchar(20) 'english_level'" json:"english_level" form:"english_level" xml:"english_level"`
	// EnglishSchool defined
	EnglishSchool null.String `xorm:"varchar(50) 'english_school'" json:"english_school" form:"english_school" xml:"english_school"`
	// IfStudy defined
	IfStudy null.Int `xorm:"int(11) 'if_study'" json:"if_study" form:"if_study" xml:"if_study"`
	// TrackingProgram defined
	TrackingProgram null.String `xorm:"varchar(200) 'tracking_program'" json:"tracking_program" form:"tracking_program" xml:"tracking_program"`
	// WastageMonth defined
	WastageMonth null.Float `xorm:"float(10,2) 'wastage_month'" json:"wastage_month" form:"wastage_month" xml:"wastage_month"`
	// Creater defined
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" form:"creater" xml:"creater"`
	// CreateDate defined
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" form:"create_date" xml:"create_date"`
	// Updater defined
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" form:"updater" xml:"updater"`
	// UpdateDate defined
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" form:"update_date" xml:"update_date"`
	// IsDelete defined
	IsDelete null.Int `xorm:"notnull 'is_delete'" json:"is_delete" form:"is_delete" xml:"is_delete"`
	// StuId defined
	StuId null.Int `xorm:"int(11) 'stu_id'" json:"stu_id" form:"stu_id" xml:"stu_id"`
}

// TableName table name of defined WastageFollowupRecord
func (m *WastageFollowupRecord) TableName() string {
	return "wastage_followup_record"
}

func (r *WastageFollowupRecord) Marshal() ([]byte, error) {
	return json.Marshal(r)
}

func UnmarshalWastageFollowupRecord(data []byte) (WastageFollowupRecord, error) {
	var r WastageFollowupRecord
	err := json.Unmarshal(data, &r)
	return r, err
}
