// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package types

import (
	"encoding/json"

	"github.com/2637309949/dolphin/packages/null"
	"github.com/shopspring/decimal"
)

// XyHourRecord defined
type XyHourRecord struct {
	// XHRId defined
	XHRId null.Int `xorm:"int(11) pk notnull autoincr 'x_h_r_id'" json:"x_h_r_id" form:"x_h_r_id" xml:"x_h_r_id"`
	// PkStu defined
	PkStu null.Int `xorm:"int(11) 'pk_stu'" json:"pk_stu" form:"pk_stu" xml:"pk_stu"`
	// CtName defined
	CtName null.String `xorm:"varchar(500) 'ct_name'" json:"ct_name" form:"ct_name" xml:"ct_name"`
	// SurplusHour defined
	SurplusHour null.Float `xorm:"float(11,2) 'surplus_hour'" json:"surplus_hour" form:"surplus_hour" xml:"surplus_hour"`
	// FinalMoney defined
	FinalMoney decimal.Decimal `xorm:"decimal(11,2) 'final_money'" json:"final_money" form:"final_money" xml:"final_money"`
	// OfStartDate defined
	OfStartDate null.Time `xorm:"datetime 'of_start_date'" json:"of_start_date" form:"of_start_date" xml:"of_start_date"`
	// OfEndDate defined
	OfEndDate null.Time `xorm:"datetime 'of_end_date'" json:"of_end_date" form:"of_end_date" xml:"of_end_date"`
	// Creater defined
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" form:"creater" xml:"creater"`
	// CreateDate defined
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" form:"create_date" xml:"create_date"`
	// Updater defined
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" form:"updater" xml:"updater"`
	// UpdateDate defined
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" form:"update_date" xml:"update_date"`
	// IsDelete defined
	IsDelete null.Int `xorm:"notnull 'is_delete'" json:"is_delete" form:"is_delete" xml:"is_delete"`
	// OfBatch defined
	OfBatch null.Int `xorm:"int(11) 'of_batch'" json:"of_batch" form:"of_batch" xml:"of_batch"`
	// CtCourseType defined
	CtCourseType null.Int `xorm:"int(11) 'ct_course_type'" json:"ct_course_type" form:"ct_course_type" xml:"ct_course_type"`
	// OfCreateDate defined
	OfCreateDate null.Time `xorm:"datetime 'of_create_date'" json:"of_create_date" form:"of_create_date" xml:"of_create_date"`
	// PkOf defined
	PkOf null.Int `xorm:"int(11) 'pk_of'" json:"pk_of" form:"pk_of" xml:"pk_of"`
	// SctIds defined
	SctIds null.String `xorm:"varchar(500) 'sct_ids'" json:"sct_ids" form:"sct_ids" xml:"sct_ids"`
}

// TableName table name of defined XyHourRecord
func (m *XyHourRecord) TableName() string {
	return "xy_hour_record"
}

func (r *XyHourRecord) Marshal() ([]byte, error) {
	return json.Marshal(r)
}

func UnmarshalXyHourRecord(data []byte) (XyHourRecord, error) {
	var r XyHourRecord
	err := json.Unmarshal(data, &r)
	return r, err
}
