// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package types

import (
	"github.com/2637309949/dolphin/packages/null"
)

// ZbxzsyxCity defined
type ZbxzsyxCity struct {
	// ZCId defined
	ZCId null.Int `xorm:"int(11) pk notnull autoincr 'z_c_id'" json:"z_c_id" form:"z_c_id" xml:"z_c_id"`
	// ZbxzsyxId defined
	ZbxzsyxId null.Int `xorm:"int(11) 'zbxzsyx_id'" json:"zbxzsyx_id" form:"zbxzsyx_id" xml:"zbxzsyx_id"`
	// OrganId defined
	OrganId null.Int `xorm:"int(11) 'organ_id'" json:"organ_id" form:"organ_id" xml:"organ_id"`
	// Creater defined
	Creater null.String `xorm:"varchar(36) 'creater'" json:"creater" form:"creater" xml:"creater"`
	// CreateDate defined
	CreateDate null.Time `xorm:"datetime 'create_date'" json:"create_date" form:"create_date" xml:"create_date"`
	// Updater defined
	Updater null.String `xorm:"varchar(36) 'updater'" json:"updater" form:"updater" xml:"updater"`
	// UpdateDate defined
	UpdateDate null.Time `xorm:"datetime 'update_date'" json:"update_date" form:"update_date" xml:"update_date"`
	// IsDelete defined
	IsDelete null.Int `xorm:"notnull 'is_delete'" json:"is_delete" form:"is_delete" xml:"is_delete"`
}

// TableName table name of defined ZbxzsyxCity
func (m *ZbxzsyxCity) TableName() string {
	return "zbxzsyx_city"
}
