app:
  name: dolphin
  mode: release
  version: "1.0"
  host: localhost:8081
  viper: false
db:
  driver: sqlite3
  datasource: ./x_test.db
  connmaxlifetime: 10
  maxidleconns: 15
  maxopenconns: 50
dir:
  app: app
  doc: doc
  log: log
  model: model
  rpc: rpc
  script: script
  sql: sql
  sqlmap: sqlmap
  srv: srv
  util: util
grpc:
  port: "9081"
http:
  hash: FF61A573-82FC-478B-9AEF-93D6F506DE9A
  port: "8081"
  prefix: /api
  static: static
oauth:
  id: Y76U9344RABF4
  secret: 8UYO6FVB8UYO6FVB
  cli: http://localhost:8081
  server: http://localhost:8081
  affirm: /static/web/affirm.html
  login: /static/web/login.html
rd:
  datasource: :111111@localhost:6379/0
swag:
  authorizationurl: /api/sys/cas/authorize
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  scope:
    admin: Grants read and write access to administrative information
    read: Grants read access
    write: Grants write access
  securitydefinitions:
    oauth2:
      accesscode: OAuth2AccessCode
  tokenurl: /api/sys/cas/token
