// Code generated by dol build. Only Generate by tools if not existed.
// source: main.go

package main

import (
	_ "github.com/2637309949/dolphin/platform/app"

	"github.com/2637309949/dolphin/packages/fx"
	_ "github.com/go-sql-driver/mysql"
)

//go:generate dolphin build sqltpl
func main() {
	fx.Run()
}
