// Code generated by dol build. Only Generate by tools if not existed.
// source: sys_table.go

package srv

import (
	"errors"
)

// SysTableAction defined srv
func SysTableAction(v interface{}) (interface{}, error) {
	return nil, errors.New("No implementation found")
}
