// Code generated by dol build. Only Generate by tools if not existed.
// source: sys_user_template_detail.go

package srv

import (
	"errors"
)

// SysUserTemplateDetailAction defined srv
func SysUserTemplateDetailAction(v interface{}) (interface{}, error) {
	return nil, errors.New("No implementation found")
}
