// Code generated by dol build. Only Generate by tools if not existed.
// source: sys_app_fun.go

package srv

import (
	"errors"
)

// SysAppFunAction defined srv
func SysAppFunAction(v interface{}) (interface{}, error) {
	return nil, errors.New("No implementation found")
}
