// Code generated by dol build. Only Generate by tools if not existed.
// source: debug.go

package srv

import (
	"errors"

	"github.com/2637309949/dolphin/packages/gin"
	"github.com/2637309949/dolphin/packages/xormplus/xorm"
)

// DebugAction defined srv
func DebugAction(ctx *gin.Context, db *xorm.Engine, params struct{}) (interface{}, error) {
	return nil, errors.New("No implementation found")
}
