// Code generated by dol build. Only Generate by tools if not existed.
// source: sys_permission.go

package srv

import (
	"errors"
)

// SysPermissionAction defined srv
func SysPermissionAction(v interface{}) (interface{}, error) {
	return nil, errors.New("No implementation found")
}
