// Code generated by dol build. Only Generate by tools if not existed.
// source: sys_role.go

package srv

import (
	"errors"
)

// SysRoleAction defined srv
func SysRoleAction(v interface{}) (interface{}, error) {
	return nil, errors.New("No implementation found")
}
