apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: platform
  name: platform
  namespace: dolphin
binaryData:
data:
  app.properties: |-
    app.name = platform
    app.mode = debug
    http.port = 8082
