app:
  auth: token
  host: http://172.20.10.3:8082
  mode: debug
  name: scene
  version: "1.0"
http:
  port: 8082
db:
  datasource: root:111111@/dolphin?charset=utf8&parseTime=True&loc=Local
  driver: mysql
redis:
  mode: stub
  addr:
  - localhost:6379
  password: ""
dtm:
  srv: http://localhost:8080/api/dtmsvr
jwt:
  secret: 6hy789iu87
  expire: 604800
oauth:
  server: http://172.20.10.3:8082
  client: http://172.20.10.3:8082
wc:
  appid: wxd1153e6068a5987d
  appsecret: 81cfff836726a497e0df15a7f9350725
rpc:
  message_srv: localhost:9081
oss:
  bucket: 965xx
  endpoint: 965xx
  accesskeyid: 965xx
  accesskeysecret: 965xx
kafka:
  broker:
  - 172.20.10.3:9092
