app:
  auth: token
  host: localhost:8081
  mode: debug
  name: scene
  version: "1.0"
http:
  port: 8082
db:
  datasource: root:111111@/dolphin?charset=utf8&parseTime=True&loc=Local
  driver: mysql
redis:
  mode: stub
  addr:
  - localhost:6379
  password: ""
dtm:
  srv: http://localhost:8080/api/dtmsvr
jwt:
  secret: 6hy789iu87
  expire: 604800
oauth:
  server: http://localhost:8082
  client: http://localhost:8082
wc:
  appid: wx756d2f0339adf67c
  appsecret: 9cc4b7928467151acea7ab1bfa0a70a7
rpc:
  message_srv: localhost:9081
oss:
  bucket: 965xx
  endpoint: 965xx
  accesskeyid: 965xx
  accesskeysecret: 965xx
kafka:
  broker:
  - 172.16.10.191:9092
