app:
  auth: token
  host: localhost:8081
  mode: release
  name: dolphin
  version: "1.0"
http:
  port: 8083
db:
  connmaxlifetime: 10
  datasource: ./x_test.db
  driver: sqlite3
  maxidleconns: 15
  maxopenconns: 50
# redis:
#   mode: stub
#   addr:
#   - localhost:6379
#   password: ""