// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

// Success defined 成功返回
type Success struct {
	// 编码
	Code int `json:"code" xml:"code"`
	// 返回数据
	Data interface{} `json:"data,omitempty" xml:"data"`
}
