definitions:
  model.Response:
    properties:
      code:
        description: 编码
        type: number
      data:
        description: 卡类型
        type: object
      msg:
        description: 消息
        type: string
    type: object
  model.User:
    properties:
      avatar:
        description: 头像
        type: string
      create_by:
        description: 创建人
        type: string
      create_time:
        description: 创建时间
        type: string
      delete_by:
        description: 删除人
        type: string
      delete_time:
        description: 删除时间
        type: string
      domain:
        description: 域
        type: string
      email:
        description: 邮箱
        type: string
      full_name:
        description: 全名
        type: string
      gender:
        description: 性别(0：女,1：男)
        type: number
      id:
        description: 主键
        type: string
      mobile:
        description: 电话
        type: string
      name:
        description: 名字
        type: string
      org_id:
        description: 组织ID
        type: string
      password:
        description: 密码
        type: string
      status:
        description: 状态(0：禁用,1：正常)
        type: number
      type:
        description: 用户类型
        type: number
      update_by:
        description: 最后更新人
        type: string
      update_time:
        description: 最后更新时间
        type: string
    type: object
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: dolphin
  version: "1.0"
paths:
  /api/user/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: query
        name: header
        required: true
        type: string
      - description: 用户信息
        in: body
        name: user
        schema:
          $ref: '#/definitions/model.User'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: 添加用户信息
      tags:
      - 用户
  /api/user/delete:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: query
        name: header
        required: true
        type: string
      - description: 用户信息id对象数组
        in: body
        name: ids
        schema:
          items:
            type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: 删除用户信息
      tags:
      - 用户
  /api/user/get:
    get:
      parameters:
      - description: 认证令牌
        in: query
        name: header
        required: true
        type: string
      - description: 用户信息id
        in: query
        name: id
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: 获取用户信息
      tags:
      - 用户
  /api/user/page:
    get:
      parameters:
      - description: 认证令牌
        in: query
        name: header
        required: true
        type: string
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 单页数
        in: query
        name: rows
        type: integer
      - description: 标题筛选
        in: query
        name: title
        type: string
      - description: 是否隐藏筛选
        in: query
        name: hidden
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: 用户信息分页查询
      tags:
      - 用户
  /api/user/update:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: query
        name: header
        required: true
        type: string
      - description: 用户信息
        in: body
        name: user
        schema:
          $ref: '#/definitions/model.User'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: 更新用户信息
      tags:
      - 用户
swagger: "2.0"
