definitions:
  model.Response:
    properties:
      code:
        description: 编码
        type: number
      data:
        description: 卡类型
        type: object
      msg:
        description: 消息
        type: string
    type: object
  model.Role:
    properties:
      code:
        description: 编码
        type: string
      create_by:
        description: 创建人
        type: string
      create_time:
        description: 创建时间
        type: string
      delete_by:
        description: 删除人
        type: string
      delete_time:
        description: 删除时间
        type: string
      domain:
        description: 域
        type: string
      id:
        description: 主键
        type: string
      name:
        description: 名称
        type: string
      status:
        description: 状态 0：禁用 1：正常
        type: number
      update_by:
        description: 最后更新人
        type: string
      update_time:
        description: 最后更新时间
        type: string
    type: object
  model.User:
    properties:
      avatar:
        description: 头像
        type: string
      create_by:
        description: 创建人
        type: string
      create_time:
        description: 创建时间
        type: string
      delete_by:
        description: 删除人
        type: string
      delete_time:
        description: 删除时间
        type: string
      domain:
        description: 域
        type: string
      email:
        description: 邮箱
        type: string
      full_name:
        description: 全名
        type: string
      gender:
        description: 性别(0：女,1：男)
        type: number
      id:
        description: 主键
        type: string
      mobile:
        description: 电话
        type: string
      name:
        description: 名字
        type: string
      org_id:
        description: 组织ID
        type: string
      password:
        description: 密码
        type: string
      salt:
        description: 盐噪点
        type: string
      status:
        description: 状态(0：禁用,1：正常)
        type: number
      type:
        description: 用户类型
        type: number
      update_by:
        description: 最后更新人
        type: string
      update_time:
        description: 最后更新时间
        type: string
    type: object
host: 127.0.0.1:8081
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: dolphin
  version: "1.0"
paths:
  /api/oauth2/affirm:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 用户授权
      tags:
      - OAuth授权
  /api/oauth2/authorize:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 用户授权
      tags:
      - OAuth授权
  /api/oauth2/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户信息
        in: body
        name: user
        schema:
          $ref: '#/definitions/model.User'
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 登录信息
      tags:
      - OAuth授权
  /api/oauth2/oauth2:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 授权回调
      tags:
      - OAuth授权
  /api/oauth2/refresh:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 刷新令牌
      tags:
      - OAuth授权
  /api/oauth2/token:
    post:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 获取令牌
      tags:
      - OAuth授权
  /api/oauth2/url:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 授权地址
      tags:
      - OAuth授权
  /api/role/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 角色信息
        in: body
        name: role
        schema:
          $ref: '#/definitions/model.Role'
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 添加角色
      tags:
      - 角色
  /api/role/get:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 角色id
        in: query
        name: id
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 获取角色信息
      tags:
      - 角色
  /api/role/page:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 单页数
        in: query
        name: size
        type: integer
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 角色分页查询
      tags:
      - 角色
  /api/role/update:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 角色信息
        in: body
        name: role
        schema:
          $ref: '#/definitions/model.Role'
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 更新角色
      tags:
      - 角色
  /api/user/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户信息
        in: body
        name: user
        schema:
          $ref: '#/definitions/model.User'
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 添加用户
      tags:
      - 用户
  /api/user/get:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户id
        in: query
        name: id
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 获取用户信息
      tags:
      - 用户
  /api/user/page:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 单页数
        in: query
        name: size
        type: integer
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 用户分页查询
      tags:
      - 用户
  /api/user/update:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户信息
        in: body
        name: user
        schema:
          $ref: '#/definitions/model.User'
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 更新用户
      tags:
      - 用户
swagger: "2.0"
