definitions:
  model.Menu:
    properties:
      code:
        description: 编码
        type: string
      component:
        description: 菜单组件
        type: string
      create_by:
        description: 创建人
        type: string
      create_time:
        description: 创建时间
        type: string
      delete_by:
        description: 删除人
        type: string
      delete_time:
        description: 删除时间
        type: string
      icon:
        description: 菜单图标
        type: string
      id:
        description: 主键
        type: string
      inheritance:
        description: 继承关系
        type: string
      name:
        description: 名称
        type: string
      order_num:
        description: 排序
        type: number
      parent:
        description: 父菜单ID，一级菜单为null
        type: string
      perms:
        description: 授权(多个用逗号分隔，如：sys:user:add,sys:user:edit)
        type: string
      type:
        description: 类型 0：目录 1：菜单 2：按钮
        type: number
      update_by:
        description: 最后更新人
        type: string
      update_time:
        description: 最后更新时间
        type: string
      url:
        description: 菜单URL,类型：1.普通页面（如用户管理， /sys/user） 2.嵌套完整外部页面，以http(s)开头的链接 3.嵌套服务器页面，使用iframe:前缀&#43;目标URL(如SQL监控，
          iframe:/druid/login.html, iframe:前缀会替换成服务器地址)
        type: string
    type: object
  model.Response:
    properties:
      code:
        description: 编码
        type: number
      data:
        description: 卡类型
        type: object
      msg:
        description: 消息
        type: string
    type: object
  model.Role:
    properties:
      code:
        description: 编码
        type: string
      create_by:
        description: 创建人
        type: string
      create_time:
        description: 创建时间
        type: string
      delete_by:
        description: 删除人
        type: string
      delete_time:
        description: 删除时间
        type: string
      domain:
        description: 域
        type: string
      id:
        description: 主键
        type: string
      name:
        description: 名称
        type: string
      status:
        description: 状态 0：禁用 1：正常
        type: number
      update_by:
        description: 最后更新人
        type: string
      update_time:
        description: 最后更新时间
        type: string
    type: object
  model.User:
    properties:
      avatar:
        description: 头像
        type: string
      create_by:
        description: 创建人
        type: string
      create_time:
        description: 创建时间
        type: string
      delete_by:
        description: 删除人
        type: string
      delete_time:
        description: 删除时间
        type: string
      domain:
        description: 域
        type: string
      email:
        description: 邮箱
        type: string
      full_name:
        description: 全名
        type: string
      gender:
        description: 性别(0：女,1：男)
        type: number
      id:
        description: 主键
        type: string
      mobile:
        description: 电话
        type: string
      name:
        description: 名字
        type: string
      org_id:
        description: 组织ID
        type: string
      password:
        description: 密码
        type: string
      salt:
        description: 盐噪点
        type: string
      status:
        description: 状态(0：禁用,1：正常)
        type: number
      type:
        description: 用户类型
        type: number
      update_by:
        description: 最后更新人
        type: string
      update_time:
        description: 最后更新时间
        type: string
    type: object
host: 127.0.0.1:8081
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: dolphin
  version: "1.0"
paths:
  /api/oauth2/affirm:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 用户授权
      tags:
      - OAuth授权
  /api/oauth2/authorize:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 用户授权
      tags:
      - OAuth授权
  /api/oauth2/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户信息
        in: body
        name: user
        schema:
          $ref: '#/definitions/model.User'
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 登录信息
      tags:
      - OAuth授权
  /api/oauth2/oauth2:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 授权回调
      tags:
      - OAuth授权
  /api/oauth2/refresh:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 刷新令牌
      tags:
      - OAuth授权
  /api/oauth2/token:
    post:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 获取令牌
      tags:
      - OAuth授权
  /api/oauth2/url:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 授权地址
      tags:
      - OAuth授权
  /api/sys/menu/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 菜单信息
        in: body
        name: menu
        schema:
          $ref: '#/definitions/model.Menu'
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 添加菜单
      tags:
      - 菜单
  /api/sys/menu/get:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 菜单id
        in: query
        name: id
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 获取菜单信息
      tags:
      - 菜单
  /api/sys/menu/list:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 单页数
        in: query
        name: size
        type: integer
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 菜单分页查询
      tags:
      - 菜单
  /api/sys/menu/tree:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 菜单树形结构
      tags:
      - 菜单
  /api/sys/menu/update:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 菜单信息
        in: body
        name: menu
        schema:
          $ref: '#/definitions/model.Menu'
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 更新菜单
      tags:
      - 菜单
  /api/sys/oauth2/affirm:
    post:
      consumes:
      - application/json
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 用户授权
      tags:
      - OAuth授权
  /api/sys/oauth2/authorize:
    get:
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 用户授权
      tags:
      - OAuth授权
  /api/sys/oauth2/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户信息
        in: body
        name: user
        schema:
          $ref: '#/definitions/model.User'
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 登录信息
      tags:
      - OAuth授权
  /api/sys/oauth2/oauth2:
    get:
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 授权回调
      tags:
      - OAuth授权
  /api/sys/oauth2/refresh:
    get:
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 刷新令牌
      tags:
      - OAuth授权
  /api/sys/oauth2/token:
    post:
      consumes:
      - application/json
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 获取令牌
      tags:
      - OAuth授权
  /api/sys/oauth2/url:
    get:
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 授权地址
      tags:
      - OAuth授权
  /api/sys/role/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 角色信息
        in: body
        name: role
        schema:
          $ref: '#/definitions/model.Role'
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 添加角色
      tags:
      - 角色
  /api/sys/role/get:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 角色id
        in: query
        name: id
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 获取角色信息
      tags:
      - 角色
  /api/sys/role/page:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 单页数
        in: query
        name: size
        type: integer
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 角色分页查询
      tags:
      - 角色
  /api/sys/role/update:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 角色信息
        in: body
        name: role
        schema:
          $ref: '#/definitions/model.Role'
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 更新角色
      tags:
      - 角色
  /api/sys/user/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 用户信息
        in: body
        name: user
        schema:
          $ref: '#/definitions/model.User'
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 添加用户
      tags:
      - 用户
  /api/sys/user/get:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 用户id
        in: query
        name: id
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 获取用户信息
      tags:
      - 用户
  /api/sys/user/page:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 单页数
        in: query
        name: size
        type: integer
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 用户分页查询
      tags:
      - 用户
  /api/sys/user/update:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 用户信息
        in: body
        name: user
        schema:
          $ref: '#/definitions/model.User'
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 更新用户
      tags:
      - 用户
swagger: "2.0"
