// Code generated by dol build. DO NOT EDIT.
const axios = require('../request').default

// tcc try
module.exports.tcc = (data = {}, opt = {}) => {
  let url = Object.assign({ url: '/api/dtm/tcc?' }, opt).url
  url = Object.keys(data).reduce((acc, curr) => `${acc}${curr}=${encodeURIComponent(data[curr])}&` ,url)
  return axios({
    url: url,
    method: 'get',
    ...opt
  })
}

// transOut try
module.exports.transOut = (data = {}, opt = {}) => {
  let url = Object.assign({ url: '/api/dtm/trans_out' }, opt).url
  if ((opt.method || 'post') === 'get') {
    url = Object.keys(data).reduce((acc, curr) => `${acc}${curr}=${encodeURIComponent(data[curr])}&` ,url)
    return axios({
      url: url,
      method: 'get',
      ...opt
    })
  }
  return axios({
    url: url,
    method: 'post',
    data,
    ...opt
  })
}

// transOutConfirm confirm
module.exports.transOutConfirm = (data = {}, opt = {}) => {
  let url = Object.assign({ url: '/api/dtm/trans_out_confirm' }, opt).url
  if ((opt.method || 'post') === 'get') {
    url = Object.keys(data).reduce((acc, curr) => `${acc}${curr}=${encodeURIComponent(data[curr])}&` ,url)
    return axios({
      url: url,
      method: 'get',
      ...opt
    })
  }
  return axios({
    url: url,
    method: 'post',
    data,
    ...opt
  })
}

// transOutRevert cancel
module.exports.transOutRevert = (data = {}, opt = {}) => {
  let url = Object.assign({ url: '/api/dtm/trans_out_revert' }, opt).url
  if ((opt.method || 'post') === 'get') {
    url = Object.keys(data).reduce((acc, curr) => `${acc}${curr}=${encodeURIComponent(data[curr])}&` ,url)
    return axios({
      url: url,
      method: 'get',
      ...opt
    })
  }
  return axios({
    url: url,
    method: 'post',
    data,
    ...opt
  })
}

// transIn try
module.exports.transIn = (data = {}, opt = {}) => {
  let url = Object.assign({ url: '/api/dtm/trans_in' }, opt).url
  if ((opt.method || 'post') === 'get') {
    url = Object.keys(data).reduce((acc, curr) => `${acc}${curr}=${encodeURIComponent(data[curr])}&` ,url)
    return axios({
      url: url,
      method: 'get',
      ...opt
    })
  }
  return axios({
    url: url,
    method: 'post',
    data,
    ...opt
  })
}

// transInConfirm confirm
module.exports.transInConfirm = (data = {}, opt = {}) => {
  let url = Object.assign({ url: '/api/dtm/trans_in_confirm' }, opt).url
  if ((opt.method || 'post') === 'get') {
    url = Object.keys(data).reduce((acc, curr) => `${acc}${curr}=${encodeURIComponent(data[curr])}&` ,url)
    return axios({
      url: url,
      method: 'get',
      ...opt
    })
  }
  return axios({
    url: url,
    method: 'post',
    data,
    ...opt
  })
}

// transInRevert cancel
module.exports.transInRevert = (data = {}, opt = {}) => {
  let url = Object.assign({ url: '/api/dtm/trans_in_revert' }, opt).url
  if ((opt.method || 'post') === 'get') {
    url = Object.keys(data).reduce((acc, curr) => `${acc}${curr}=${encodeURIComponent(data[curr])}&` ,url)
    return axios({
      url: url,
      method: 'get',
      ...opt
    })
  }
  return axios({
    url: url,
    method: 'post',
    data,
    ...opt
  })
}

