// Code generated by dol build. DO NOT EDIT.
const axios = require('../request').default

// add Add article
module.exports.add = (data = {}, opt = {}) => {
  let url = Object.assign({ url: '/api/nsq/add' }, opt).url
  if ((opt.method || 'post') === 'get') {
    url = Object.keys(data).reduce((acc, curr) => `${acc}${curr}=${encodeURIComponent(data[curr])}&` ,url)
    return axios({
      url: url,
      method: 'get',
      ...opt
    })
  }
  return axios({
    url: url,
    method: 'post',
    data,
    ...opt
  })
}

// get Get Nsq info
module.exports.get = (data = {}, opt = {}) => {
  let url = Object.assign({ url: '/api/nsq/get?' }, opt).url
  url = Object.keys(data).reduce((acc, curr) => `${acc}${curr}=${encodeURIComponent(data[curr])}&` ,url)
  return axios({
    url: url,
    method: 'get',
    ...opt
  })
}

