// Code generated by dol build. DO NOT EDIT.
const axios = require('../request').default

// selectone 测试selectone
module.exports.selectone = (data = {}, opt = {}) => {
  let url = opt.url || '/api/sqlmap/selectone?'
  for (var key in data) {
    url += key + '=' + encodeURIComponent(data[key]) + '&'
  }
  return axios({
    url: url,
    method: 'get',
    ...opt
  })
}

