// Code generated by dol build. DO NOT EDIT.
const axios = require('../request').default

// like like article
module.exports.like = (data = {}, opt = {}) => {
  const url = opt.url ||  '/api/vote/like'
  if ((opt.method || 'post') === 'get') {
    for (var key in data) {
      url += key + '=' + encodeURIComponent(data[key]) + '&'
    }
    return axios({
      url: url,
      method: 'get',
      ...opt
    })
  }
  return axios({
    url: url,
    method: 'post',
    data,
    ...opt
  })
}

