apiVersion: v1
kind: Deployment
metadata:
  name: demo
  namespace: dolphin
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: registry.cn-hangzhou.aliyuncs.com/demo:1001
        volumeMounts:
          - name: config
            mountPath: /app/app.properties
            subPath: app.properties
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "10Mi"
            cpu: "11m"
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: registrykey
      volumes:
        - name: config
          configMap:
            name: demo