// Code generated by dol build. Only Generate by tools if not existed.
// source: activity.go

package srv

import (
	"errors"
)

// ActivityAction defined srv
func ActivityAction(v interface{}) (interface{}, error) {
	return nil, errors.New("No implementation found")
}
