// Code generated by dol build. DO NOT EDIT.
// source: auto.go

const axios = require('../axios')


// Add 添加数据权限
module.exports.Add = (data) => {
	const url = '/api/sys/data/permission/add'
	return axios({
		url: url,
		method: 'post',
		data
    })
}

// Del 删除数据权限
module.exports.Del = (data) => {
	const url = '/api/sys/data/permission/del'
	return axios({
		url: url,
		method: 'delete',
		data
    })
}

// Update 更新数据权限
module.exports.Update = (data) => {
	const url = '/api/sys/data/permission/update'
	return axios({
		url: url,
		method: 'put',
		data
    })
}

// Page 数据权限分页查询
module.exports.Page = (data) => {
	const url = '/api/sys/data/permission/page'
	return axios({
		url: url,
		method: 'get',
		data
    })
}

// Get 获取数据权限信息
module.exports.Get = (data) => {
	const url = '/api/sys/data/permission/get'
	return axios({
		url: url,
		method: 'get',
		data
    })
}

