definitions:
  model.Activity:
    properties:
      campus:
        description: 校区
        type: string
      content:
        description: 内容
        type: string
      create_by:
        description: 创建人
        type: string
      create_time:
        description: 创建时间
        type: string
      delete_by:
        description: 删除人
        type: string
      delete_time:
        description: 删除时间
        type: string
      forward_count:
        description: 转发次数
        type: number
      hidden:
        description: 是否隐藏 0(否) 1(是)
        type: number
      id:
        description: 主键
        type: string
      image:
        description: 图片
        type: string
      is_entry:
        description: 是否报名 0(否) 1(是)
        type: number
      like_count:
        description: 点赞次数
        type: number
      priority:
        description: 优先级
        type: number
      read_count:
        description: 阅读次数
        type: number
      share_count:
        description: 分享次数
        type: number
      title:
        description: 标题
        type: string
      type:
        description: 类型
        type: number
      update_by:
        description: 最后更新人
        type: string
      update_time:
        description: 最后更新时间
        type: string
    type: object
  model.Response:
    properties:
      code:
        description: 编码
        type: number
      data:
        description: 卡类型
        type: object
      msg:
        description: 消息
        type: string
    type: object
  model.Role:
    properties:
      code:
        description: 编码
        type: string
      create_by:
        description: 创建人
        type: string
      create_time:
        description: 创建时间
        type: string
      delete_by:
        description: 删除人
        type: string
      delete_time:
        description: 删除时间
        type: string
      domain:
        description: 域
        type: string
      id:
        description: 主键
        type: string
      name:
        description: 名称
        type: string
      status:
        description: 状态 0：禁用 1：正常
        type: number
      update_by:
        description: 最后更新人
        type: string
      update_time:
        description: 最后更新时间
        type: string
    type: object
  model.User:
    properties:
      avatar:
        description: 头像
        type: string
      create_by:
        description: 创建人
        type: string
      create_time:
        description: 创建时间
        type: string
      delete_by:
        description: 删除人
        type: string
      delete_time:
        description: 删除时间
        type: string
      domain:
        description: 域
        type: string
      email:
        description: 邮箱
        type: string
      full_name:
        description: 全名
        type: string
      gender:
        description: 性别(0：女,1：男)
        type: number
      id:
        description: 主键
        type: string
      mobile:
        description: 电话
        type: string
      name:
        description: 名字
        type: string
      org_id:
        description: 组织ID
        type: string
      password:
        description: 密码
        type: string
      salt:
        description: 盐噪点
        type: string
      status:
        description: 状态(0：禁用,1：正常)
        type: number
      type:
        description: 用户类型
        type: number
      update_by:
        description: 最后更新人
        type: string
      update_time:
        description: 最后更新时间
        type: string
    type: object
host: 127.0.0.1:8081
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: example
  version: "1.0"
paths:
  /api/activity/add_many:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 活动对象
        in: body
        name: activity
        schema:
          items:
            $ref: '#/definitions/model.Activity'
          type: array
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: 添加活动
      tags:
      - 活动
  /api/activity/add_one:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 活动对象
        in: body
        name: activity
        schema:
          $ref: '#/definitions/model.Activity'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: 添加活动
      tags:
      - 活动
  /api/activity/delete_many:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 活动对象
        in: body
        name: activity
        schema:
          items:
            $ref: '#/definitions/model.Activity'
          type: array
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: 删除活动
      tags:
      - 活动
  /api/activity/delete_one:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 活动对象
        in: body
        name: activity
        schema:
          $ref: '#/definitions/model.Activity'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: 删除活动
      tags:
      - 活动
  /api/activity/list:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 单页数
        in: query
        name: size
        type: integer
      - description: 标题筛选
        in: query
        name: title
        type: string
      - description: 是否隐藏筛选
        in: query
        name: hidden
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: 活动分页查询
      tags:
      - 活动
  /api/activity/one:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 活动id
        in: query
        name: id
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: 获取活动
      tags:
      - 活动
  /api/activity/update_many:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 活动对象
        in: body
        name: activity
        schema:
          items:
            $ref: '#/definitions/model.Activity'
          type: array
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: 更新活动
      tags:
      - 活动
  /api/activity/update_one:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 活动对象
        in: body
        name: activity
        schema:
          $ref: '#/definitions/model.Activity'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: 更新活动
      tags:
      - 活动
  /api/oauth2/affirm:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 用户授权
      tags:
      - OAuth授权
  /api/oauth2/authorize:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 用户授权
      tags:
      - OAuth授权
  /api/oauth2/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户信息
        in: body
        name: user
        schema:
          $ref: '#/definitions/model.User'
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 登录信息
      tags:
      - OAuth授权
  /api/oauth2/oauth2:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 授权回调
      tags:
      - OAuth授权
  /api/oauth2/refresh:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 刷新令牌
      tags:
      - OAuth授权
  /api/oauth2/token:
    post:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 获取令牌
      tags:
      - OAuth授权
  /api/oauth2/url:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 授权地址
      tags:
      - OAuth授权
  /api/role/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 角色信息
        in: body
        name: role
        schema:
          $ref: '#/definitions/model.Role'
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 添加角色
      tags:
      - 角色
  /api/role/get:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 角色id
        in: query
        name: id
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 获取角色信息
      tags:
      - 角色
  /api/role/page:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 单页数
        in: query
        name: size
        type: integer
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 角色分页查询
      tags:
      - 角色
  /api/role/update:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        type: string
      - description: 角色信息
        in: body
        name: role
        schema:
          $ref: '#/definitions/model.Role'
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 更新角色
      tags:
      - 角色
  /api/user/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户信息
        in: body
        name: user
        schema:
          $ref: '#/definitions/model.User'
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 添加用户
      tags:
      - 用户
  /api/user/get:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户id
        in: query
        name: id
        type: string
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 获取用户信息
      tags:
      - 用户
  /api/user/page:
    get:
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 单页数
        in: query
        name: size
        type: integer
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 用户分页查询
      tags:
      - 用户
  /api/user/update:
    post:
      consumes:
      - application/json
      parameters:
      - description: 认证令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户信息
        in: body
        name: user
        schema:
          $ref: '#/definitions/model.User'
      responses:
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
      summary: 更新用户
      tags:
      - 用户
  /api/v1/activity/in_crease:
    get:
      parameters:
      - description: 记录id
        in: query
        name: id
        type: string
      - description: 点赞（like）,分享（share）和收藏(collect) 收藏和点赞第一次调用次数增一，调第二次减一，分享每一次都加一
        in: query
        name: action
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: 增加次数
      tags:
      - 活动
  /api/v2/activity/in_crease_v2:
    post:
      consumes:
      - application/json
      parameters:
      - description: 记录id
        in: body
        name: id
        schema:
          type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: 增加次数
      tags:
      - 活动
swagger: "2.0"
