// Code generated by dol build. DO NOT EDIT.
// source: auto.go
const axios = require('@/utils/request')

// Add 添加角色
module.exports.Add = (data) => {
  const url = '/api/sys/role/add'
  return axios({
    url: url,
    method: 'post',
    data
  })
}

// Del 删除角色
module.exports.Del = (data) => {
  const url = '/api/sys/role/del'
  return axios({
    url: url,
    method: 'delete',
    data
  })
}

// Update 更新角色
module.exports.Update = (data) => {
  const url = '/api/sys/role/update'
  return axios({
    url: url,
    method: 'put',
    data
  })
}

// Page 角色分页查询
module.exports.Page = (data) => {
  let url = '/api/sys/role/page?'
  for (var key in data) {
    url += key + '=' + data[key] + '&'
  }
  return axios({
    url: url,
    method: 'get'
  })
}

// Get 获取角色信息
module.exports.Get = (data) => {
  let url = '/api/sys/role/get?'
  for (var key in data) {
    url += key + '=' + data[key] + '&'
  }
  return axios({
    url: url,
    method: 'get'
  })
}

