// Code generated by dol build. DO NOT EDIT.
// source: auto.go
const axios = require('@/utils/request')

// Add 添加附件
module.exports.Add = (data) => {
  const url = '/api/sys/attachment/add'
  return axios({
    url: url,
    method: 'post',
    data
  })
}

// Upload 上传附件
module.exports.Upload = (data) => {
  const url = '/api/sys/attachment/upload'
  return axios({
    url: url,
    method: 'post',
    data
  })
}

// Del 删除附件
module.exports.Del = (data) => {
  const url = '/api/sys/attachment/del'
  return axios({
    url: url,
    method: 'delete',
    data
  })
}

// Update 更新附件
module.exports.Update = (data) => {
  const url = '/api/sys/attachment/update'
  return axios({
    url: url,
    method: 'put',
    data
  })
}

// Page 附件分页查询
module.exports.Page = (data) => {
  let url = '/api/sys/attachment/page?'
  for (var key in data) {
    url += key + '=' + data[key] + '&'
  }
  return axios({
    url: url,
    method: 'get'
  })
}

// Get 获取附件信息
module.exports.Get = (data) => {
  let url = '/api/sys/attachment/get?'
  for (var key in data) {
    url += key + '=' + data[key] + '&'
  }
  return axios({
    url: url,
    method: 'get'
  })
}

