// Code generated by dol build. DO NOT EDIT.
const axios = require('@/utils/request').default

// add 添加表字段
module.exports.add = (data = {}, opt = {}) => {
  const url = opt.url ||  '/api/sys/table/column/add'
  if ((opt.url || 'post') === 'get') {
    for (var key in data) {
      url += key + '=' + encodeURIComponent(data[key]) + '&'
    }
    return axios({
      url: url,
      method: 'get',
      ...opt
    })
  }
  return axios({
    url: url,
    method: 'post',
    data,
    ...opt
  })
}

// del 删除表字段
module.exports.del = (data = {}, opt = {}) => {
  const url = opt.url ||  '/api/sys/table/column/del'
  if ((opt.url || 'delete') === 'get') {
    for (var key in data) {
      url += key + '=' + encodeURIComponent(data[key]) + '&'
    }
    return axios({
      url: url,
      method: 'get',
      ...opt
    })
  }
  return axios({
    url: url,
    method: 'delete',
    data,
    ...opt
  })
}

// batchDel 删除表字段
module.exports.batchDel = (data = {}, opt = {}) => {
  const url = opt.url ||  '/api/sys/table/column/batch_del'
  if ((opt.url || 'delete') === 'get') {
    for (var key in data) {
      url += key + '=' + encodeURIComponent(data[key]) + '&'
    }
    return axios({
      url: url,
      method: 'get',
      ...opt
    })
  }
  return axios({
    url: url,
    method: 'delete',
    data,
    ...opt
  })
}

// update 更新表字段
module.exports.update = (data = {}, opt = {}) => {
  const url = opt.url ||  '/api/sys/table/column/update'
  if ((opt.url || 'put') === 'get') {
    for (var key in data) {
      url += key + '=' + encodeURIComponent(data[key]) + '&'
    }
    return axios({
      url: url,
      method: 'get',
      ...opt
    })
  }
  return axios({
    url: url,
    method: 'put',
    data,
    ...opt
  })
}

// page 表字段分页查询
module.exports.page = (data = {}, opt = {}) => {
  let url = opt.url || '/api/sys/table/column/page?'
  for (var key in data) {
    url += key + '=' + encodeURIComponent(data[key]) + '&'
  }
  return axios({
    url: url,
    method: 'get',
    ...opt
  })
}

// get 获取表字段信息
module.exports.get = (data = {}, opt = {}) => {
  let url = opt.url || '/api/sys/table/column/get?'
  for (var key in data) {
    url += key + '=' + encodeURIComponent(data[key]) + '&'
  }
  return axios({
    url: url,
    method: 'get',
    ...opt
  })
}

