// Code generated by dol build. DO NOT EDIT.
// source: auto.go

package model

import (
	"github.com/2637309949/dolphin/packages/null"
)

// McVote defined
type McVote struct {
	// UserId defined 用户ID
	UserId null.Int `xorm:"int(11) notnull comment('用户ID') 'user_id'" json:"user_id" form:"user_id" xml:"user_id"`
	// VotableId defined 投票目标ID
	VotableId null.Int `xorm:"int(11) notnull comment('投票目标ID') 'votable_id'" json:"votable_id" form:"votable_id" xml:"votable_id"`
	// VotableType defined 投票目标类型 question、answer、article、comment
	VotableType null.String `xorm:" notnull comment('投票目标类型 question、answer、article、comment') 'votable_type'" json:"votable_type" form:"votable_type" xml:"votable_type"`
	// Type defined 投票类型 up、down
	Type null.String `xorm:" notnull comment('投票类型 up、down') 'type'" json:"type" form:"type" xml:"type"`
	// CreateTime defined 投票时间
	CreateTime null.Int `xorm:"int(10) notnull comment('投票时间') 'create_time'" json:"create_time" form:"create_time" xml:"create_time"`
}

// TableName table name of defined McVote
func (m *McVote) TableName() string {
	return "mc_vote"
}
